### ISSUE TITLE
aotf: mutation associated with the wrong workflow

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1006]
Spotted with the released `1.1.0`.

The mutation menu is shown for the wrong workflow:

![Screenshot from 2022-05-05 10-26-05](https://user-images.githubusercontent.com/16705946/166896434-09aec574-d1ff-4a9b-9db1-9eee9252782d.png)

I had a list of workflows and "cleaned" them one by one. The problem only occurred for the last workflow.

This looks very similar to https://github.com/cylc/cylc-ui/issues/690

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
(was fine after reload)

**Comment by MetRonnie** [comment]
I can reproduce. Looks like recent changes to the `cylc-object-menu` directive's `bind` function may have re-introduced #690

**Comment by hjoliver** [comment]
(Also acts on the wrong/previous workflow).
