### ISSUE TITLE
scan side-panel width

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#1035]
Not sure if this design issue has come up yet.

If workflow names are too long, and you install with `--no-run-name`, the name will push the job icons off to the right. Even more so if you crank the font size up in UI preferences.

Can we make the row of icons drop down to the next line, if it overruns the panel? Otherwise we'll need to allow users to adjust the width.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/2362137/170618987-1c5e4a3f-aa6e-4c71-9fda-9ba97fd1ff1f.png)

**Comment by oliver-sanders** [comment]
> Can we make the row of icons drop down to the next line, if it overruns the panel?

We tried this, it's quite jarring.

> Otherwise we'll need to allow users to adjust the width.

:+1:
