### ISSUE TITLE
Configurable default workflow view

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#1036]
A user (this one: https://github.com/cylc/cylc-ui/issues/1035#issue-1250273673 ) wants to be able to make the table view the default view. 

I imagine that would be easy to implement via Preferences, without waiting for full tab layout preservation.

(This might already be covered by another Issue?).

**Comment by oliver-sanders** [comment]
Closely related to https://github.com/cylc/cylc-ui/issues/662.

To solve properly, we need a system for serialising/deserialising the lumino layout, e.g:

```js
{
    'views': [
       {
            'name': 'table',
            'location': [0, 25, 0, 100],  // left%, right%, top%, bottom%
            'state': {  // i.e. the Vue component state
                'filters': {
                     'name': null,
                     'states': ['failed']
                 }
            }
       },
    ]
}
```

At the moment UI config is held in browser "local storage", to preserve this config properly we also need a user configuration file - https://github.com/cylc/cylc-uiserver/issues/232

**Comment by hjoliver** [comment]
> I imagine that would be easy to implement via Preferences, without waiting for full tab layout preservation.

To be clearer this issue is to consider simply allowing users to choose Table instead of Tree as the default view when clicking on a workflow in the gscan sidebar. 

Whether or not we do this (which is super easy), I think, should depend on how soon we can get full tab layout preservation done.

In fact, the two might be orthogonal. This could set the default view when no layout has been saved by the user.
