### ISSUE TITLE
suite listing: load bar flickering every ~1-5s

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-ui#104]
In the single user suite listing, i.e. at ``.../user/<user>/#/suites``, there is a thin green horizontal load bar that momentarily appears every 1-5 seconds or so (not at a constant rate, & I cannot immediately see anything that may be causing a flicker to go off) directly under the table headings. (It's too quick for me to capture it in a screenshot).

This is distracting & annoying, so we should prevent it from showing.

**Comment by hjoliver** [comment]
I noticed this too.  We are not going to have this suite listing view in the final UI anyway (it will be the left "gscan" side bar) ... but no harm in fixing it for now!

**Comment by kinow** [comment]
That should be done with WebSockets as well. But I agree it is annoying, and fixing it would be really great! :grimacing: 

From what I recall, we are replacing the data that is used by a vuetify table component. The table has also an option to display the loading bar, and that may be causing the issue as well.

Might be a matter of just checking if we are not doing something wrong by replacing the `data` value, or if we are misusing the table component.
