### ISSUE TITLE
aotf: Mutation form order

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1055]
**Describe exactly what you would like to see in an upcoming release**

The alphabetical sort order of the mutation form is not necessarily the most useful order. If we don't sort the items will they just follow the schema order?

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
> If we don't sort the items will they just follow the schema order?

Sadly I don't think the definition order is preserved.

**Comment by oliver-sanders** [comment]
Related to https://github.com/cylc/cylc-ui/issues/647

**Comment by oliver-sanders** [comment]
Double checked, no we cannot preserve definition order because GraphQL/Graphene does not preserve definition order itself.

```graphql
query {
  __schema {
	mutationType {
    name
    fields {
      name
      args {
        name
      }
    }
  }
  }
}
```

```json
{
  "data": {
    "__schema": {
      "mutationType": {
        "name": "UISMutations",
        "fields": [
          {
            "name": "broadcast",
            "args": [
              {
                "name": "cutoff"
              },
              {
                "name": "cyclePoints"
              },
              {
                "name": "mode"
              },
              {
                "name": "namespaces"
              },
              {
                "name": "settings"
              },
              {
                "name": "workflows"
              }
            ]
          },
```

**Comment by oliver-sanders** [comment]
We should investigate defining a sort order client-side. I think this will probably do a fairly good job of it #1057.

**Comment by oliver-sanders** [comment]
Superseded by #1057
