### ISSUE TITLE
Offline mode: table view incorrect most recent job icon

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1066]
Spotted in offline testing, the collated job icon does not match the most recent job status.

Genuine issue with the table view (1.3.0 milestone) or smaller issue with the offline test mode (1.4.0 milestone)?

**Steps to reproduce:**

```console
$ yarn run serve
```

Open the table view, the job icon next to the task icon should show the most recent job (where multiple jobs are present a multi-job stack icon should also show the status of the previous job).

At the moment the most recent job is shown as submitted for all tasks:

![Screenshot from 2022-07-20 10-21-19](https://user-images.githubusercontent.com/16705946/179946833-f9527406-5c72-41eb-aa24-5f7c36da99e6.png)

**Pull requests welcome!**

**Comment by wxtim** [comment]
Can't replicate this with live data - :. can push it to a later milestone.
