### ISSUE TITLE
task: clockface alignment broken in webkit/safari

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1078]
The clockface alignment has become broken in webkit/safari when zooming in/out:

<img width="663" alt="Screenshot 2022-07-27 at 09 14 37" src="https://user-images.githubusercontent.com/16705946/181197216-1f0bc8ad-7572-4b2c-a333-ee9d3f23e222.png">

At 100% the alignment is correct.

See also #178 

**Pull requests welcome!**

**Comment by wxtim** [comment]
I've tried this on RHEL7 Firefox and can't replicate it. Also tried using ctrl + and ctrl -.

**Comment by MetRonnie** [comment]
I can't reproduce on Chrome or Firefox

**Comment by wxtim** [comment]
I have reproduced this and confirmed that #1108 fixes it too. :)
