### ISSUE TITLE
Cypress e2e tests for table view

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-ui#1091]
**Describe exactly what you would like to see in an upcoming release**

Add end-to-end testing of the table view.

To do this (without affecting existing tests) we will want to add additional canned workflows, not least one with >1 active cycle points.

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
See also #952

**Comment by MetRonnie** [comment]
I've added the point about having >1 cycle so now I think this can be closed as a duplicate of #952
