### ISSUE TITLE
Make hit area of mutation (aka command) edit button bigger

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1096]
**Describe exactly what you would like to see in an upcoming release**

The "edit" button in the command menu has an unreasonably small hit area. It is too easy to submit the command when trying to click the edit button.

![image](https://user-images.githubusercontent.com/61982285/184356032-bfd1561e-926f-4bf3-a19f-910c312a1d4d.png)

**Pull requests welcome!**

**Comment by wxtim** [comment]
Have a look and see if https://github.com/cylc/cylc-ui/pull/1097 answers before I waste time trying to do something cleverer like making the action area a rectangle filling the whole of the right hand quarter of the surrounding element.
