### ISSUE TITLE
Trigger edit replacement - "Edit Runtime"

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1104]
As discussed in https://github.com/cylc/cylc-flow/issues/3751, implement the front-end of trigger-edit capability. This will take the task's `[runtime]` info from GraphQL (https://github.com/cylc/cylc-flow/issues/5054) and display it as a form, allowing user to add/remove/edit fields (but not the `inherit` field).

**Comment by hjoliver** [comment]
A note, offline, from one of our main sites:  

> our most common edit run is to change a line that looks like:
> `rose task-run arg1 arg2 arg3`
>       to
> `rose task-run arg1 arg2 arg3 –new`
>       To force something to re-run from scratch (for example if the model was unstable)

Probably stating the obvious at this point, but the `script` items will need text-edit capability, potentially for a large amount of scripting.

**Comment by hjoliver** [comment]
What did we decide to rename this capability to, now that "trigger edit" and "edit run" are no longer appropriate (triggering will be separate)?
 
- stick with `broadcast`, for former use cases of that **and** for the more restricted one-off "edit run" style use?
   - this name is a fairly obtuse reference to how it works under the hood, but it might not be so obvious to users
- `set-runtime` or `task-runtime`?
- `override`?
- ???

**Comment by hjoliver** [comment]
Security concerns?

Initially I guess we can just make sure `cylc broadcast` defaults to the most restrictive authorization level. 

Later we might need to consider separating out the ability to run arbitrary code via `script` items (and potentially environment variable assignment)

**Comment by hjoliver** [comment]
Note security concerns here: https://github.com/cylc/cylc-flow/issues/2687#issuecomment-641893745

Initially, I guess we can just make sure `cylc broadcast` as a whole defaults to the most restrictive authorization level. 

Later we might need to consider singling out `script` and `environment` items as more dangerous.

**Comment by MetRonnie** [comment]
> What did we decide to rename this capability to, now that "trigger edit" and "edit run" are no longer appropriate (triggering will be separate)?

I had settled upon "Edit Runtime", but open to suggestions

**Comment by hjoliver** [comment]
Right, thanks, I recall that from the meeting now.  "Edit Runtime" is quite good - it is descriptive and it's reminiscent of the original "edit run" description of "trigger --edit".

We should consider changing the CLI command name `cylc broadcast` to `cylc edit-runtime` too. (We can provide an alias to the old name, of course).
