### ISSUE TITLE
static graph view: issues when leaving page

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-ui#112]
In the current ``master`` Static Graph View (which I appreciate is in a very early stage) there are a few issues I have noticed regarding leaving the Graph View page.

1. **Mostly blank page on return:** If you access & then leave it by changing page (via the sidebar menu or specifying some non-root URL), then return to the Graph VIew page, the graph & the top-left navigation bar both disappear (though you can still see the "minimap"). (However, if you specify & go to the root URL ``localhost:8000/user/<user>`` & access the Graph View after that, it is displayed again.) Example screenshot:

    ![bruno_new_scr](https://user-images.githubusercontent.com/30274190/60925957-f9241480-a29c-11e9-9b82-ab0a76d60e5e.png)

2. **Persistent task node information boxes:** You can click on a task node to view information about it in a box. Whilst still on the Graph View page, you can click away from the graph in the blank surrounding area & it will disappear. But if you change page  whilst a box is still up, it will stay up on the page & you cannot get rid of it (except, as above, by setting the browser to return to the root URL):

    ![sticky_node_!](https://user-images.githubusercontent.com/30274190/60924785-f5db5980-a299-11e9-830d-f8fec484aa3f.png)
    ![sticky_node_2](https://user-images.githubusercontent.com/30274190/60924784-f5db5980-a299-11e9-8b0e-991fff4f508e.png)

Due to other priorities I cannot investigate this yet, but I suspect it is a problem relating to the router paths.

**Comment by kinow** [comment]
There is a comment from @MartinRyan somewhere (Riot or GitHub), where he mentions he was having issues with back/history and the data for the graphs. So I think he was aware, but didn't have time to fix it.

Could be an issue by reusing some Cytoscape component after the data has been deleted (though the persistent box is new for me, hadn't spotted that one before, nice one)

Thanks Sadie!
Bruno

**Comment by sadielbartholomew** [comment]
Thanks for the explanation, @kinow! I am going to sleep now, but have just spotted a line which I think will  be causing this, 31 as below:
https://github.com/cylc/cylc-ui/blob/e68f91b9410b5508c8e0fb6f780a9c765ed4638e/src/router/paths.js#L27-L32

The graph page is aliased to the root! Not sure why Martin added that in (there are probably reasons?) but this is bound to cause problems.

**Comment by kinow** [comment]
That doesn't look right! I just changed locally, and after opening the Graph view, then going back to dashboard, and back to Graph again, it was still broken.

But we should remove that alias anyway.

It could have been copy-paste issue (copying from some of my code elsewhere perhaps), or he had the main page displaying the graph to make it easier/quicker to develop the component.

**Comment by MartinRyan** [comment]
I just created a pull request to fix tooltips hanging around after navigating away from the graph view and an a fix for undo, I'm finding the reload of the graph view issue a little more intractable.

**Comment by kinow** [comment]
@MartinRyan I had a quick look at the PR, but did not check out the code locally. I have a guess at how this could be solved, but will only have time to try it after this Friday.

My guess is that creating a `src/views/Graph.vue`, and another `src/components/cylc/Graph.vue`, will make this issue disappear.

This view/component bound to `/#/graph` is always re-rendered (views with parameters or created with `<keep-alive>` are not always re-rendered).

I think the current `Graph.vue` has code to handle both view navigation and lifecycle, and component lifecycle. Once moved, I guess the new `src/components/cylc/Graph.vue` will behave better - I suspect we will have to do it anyway later.

**Comment by MartinRyan** [comment]
addresses graph reload https://github.com/cylc/cylc-ui/pull/182

**Comment by hjoliver** [comment]
> addresses graph reload #182

@MartinRyan - do you mean #182 addresses this Issue?  (if so, I guess we can close this one?)

**Comment by MartinRyan** [comment]
yes @hjoliver
