### ISSUE TITLE
mutation menu: menu should scroll

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1120]
The mutation menu can get quite long when hidden options are shown.

Currently it can go off the end of the page causing vertical scrolling. Instead it should scroll *within* the menu when there is insufficient space.

![Screenshot from 2022-10-20 16-30-52](https://user-images.githubusercontent.com/16705946/196992959-b070b3f1-f4c7-4643-b07b-bfa78eb6e69a.png)

**Pull requests welcome!**

**Comment by wxtim** [comment]
I've had an unsuccessful play with this. Setting 

```diff
- <v-card ref="menuContent">
+ <v-card ref="menuContent" max-height="70vh">
```

Works fine as long as the clicked location is near the top the page. If not, the initial mutations menu is bounded by the page bottom, but the extended version isn't.
