### ISSUE TITLE
table: increase rows per page

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1121]
The default number of rows-per-page is 10, which is quite low. From the dropdown we have the option to change this to 5, 10, 15 or all.

I would suggest values like 50, 100, 200 (& all) would be more appropriate for this view.

When attempting this do some quick testing to ensure the table view performance is acceptable for the pre-defined values.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Maybe leave 10 as the lowest, to avoid the need for scrolling on small screens (or small tabs).

10, 50, 100, 200, all

**Comment by hjoliver** [comment]
Yes, but given that we have a paginated table, it's better to simply click on 'next' to get the next page, rather than have to scroll to find `next` before clicking on it.

**Comment by wxtim** [comment]
Looking into this I came across [this StackOverflow thread](https://stackoverflow.com/questions/59759939/vuetify-show-pagination-controls-at-the-top-of-my-v-data-table-as-well-as-in-th) which claims that it's possible to move these controls to the top of the table component. I got it working enough that I though it might be worth an investigate later. What do you thing @hjoliver ?

**Comment by oliver-sanders** [comment]
Alternatively you could put the controls in a sticky footer.

**Comment by wxtim** [comment]
For reference with and without dense turned on.

![Screen Shot 2022-10-25 at 15 48 57](https://user-images.githubusercontent.com/26465611/198040805-cdf7d6bd-72c8-4ec4-9a19-1232ecdf8cd7.png)
![Screen Shot 2022-10-25 at 15 50 32](https://user-images.githubusercontent.com/26465611/198040816-41584149-2cea-4015-b9f1-12229c67823d.png)
