### ISSUE TITLE
alert: error icon looks like close button

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1127]
The error icon in alerts looks somewhat like a close icon:

<img width="929" alt="Screenshot 2022-10-27 at 16 08 26" src="https://user-images.githubusercontent.com/16705946/198327761-f3793da8-1b43-40e4-be0e-1115502b7443.png">

Suggest using something like ⚠️, ⛔️ or 😞.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
IMO we should also replace the whole error bar with a [snackbar](https://vuetifyjs.com/en/components/snackbars/) (toast-like pop-up). This is already in use for the Edit Runtime form (#1160).

The problem with the current error bar is it causes a downward shift of the open view.

**Comment by oliver-sanders** [comment]
I'd be happy to re-work the Alert component to use a snackbar. We should push the edit-runtime alerts through this system when done.
