### ISSUE TITLE
outputs: task outputs can be mapped onto all jobs

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1129]
The tree view associates task outputs with the jobs which created them.

In this example I have a task which fails twice before succeeding, each time it generates *one* output.

```ini
[runtime]
    [[foo]]
        script = """
            if [[ $CYLC_TASK_TRY_NUMBER -eq 1 ]]; then
                cylc message -- loscil
                false
            elif [[ $CYLC_TASK_TRY_NUMBER -eq 2 ]]; then
                cylc message -- biosphere
                false
            else
                cylc message -- gas
            fi
        """
```

If I watch this task in the GUI I see one output associated with the first job (correct), two with the second (incorrect) and three with the third (incorrect).

Curiously when I refresh the page I see all three outputs associated with all three jobs (really incorrect).

![outputs-bug](https://user-images.githubusercontent.com/16705946/199787204-f445b3fd-729d-40c7-b3a1-8206da9f2911.gif)

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Will see if I can close this whilst fixing outputs in the data-store/graph view PR.

**Comment by dwsutherland** [comment]
Maybe job level outputs are being set with task level outputs (?)

**Comment by oliver-sanders** [comment]
It was a UI bug, the task outputs needed to be filtered by the job messages to work out which outputs had been created by which job, sorted now in the graph view PR.
