### ISSUE TITLE
Mutations Menu: Jumps on expand

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-ui#1163]
**Describe the bug**
When expanded off the bottom of the screen the mutations menu jumps upward to fit the screen.

**Steps to reproduce the bug**
Click on a menu task icon near the bottom of the screen. Expand the menu.

**Expected behavior**
The menu should be in it's final position on expanding.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
High priority but we're not going to have a fix ready in time so bumping back.
