### ISSUE TITLE
GScan: filtering by initial part of multi-level workflow name does not work

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1173]
**Describe the bug**
In the GScan sidebar, typing in `bunny` or `rabbit` into the filter text input will not result in the workflow called `bunny/rabbit/run1` being shown.

**Release version(s) and/or repository branch(es) affected?**
master / 1.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/61982285/208150682-b5f2bacd-218b-44fa-9e9a-746240e430ca.png)

![image](https://user-images.githubusercontent.com/61982285/208150750-5c195701-b6b7-4910-a026-bf1eb1d97058.png)

![image](https://user-images.githubusercontent.com/61982285/208150823-5bfff385-6cc1-42a3-bdd8-bb66daf150b9.png)

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
MB, easy fix.
