### ISSUE TITLE
Create Cylc header component

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#120]
For #116, in the left top corner, what we have right now needs to be replaced by this new component.

![image](https://user-images.githubusercontent.com/304786/61019538-a8243580-a3ee-11e9-9e0d-874ff8548b0d.png)

Now it must contain the Cylc logo, and the user name and host name.

![image](https://user-images.githubusercontent.com/304786/61019685-2d0f4f00-a3ef-11e9-8730-02bd9ba8546d.png)

**Comment by kinow** [comment]
![logo-exeter-design](https://user-images.githubusercontent.com/304786/61194384-2e08ef00-a715-11e9-9cf7-084f27fe2da7.png)

Extracted logo from the PDF.

**Comment by hjoliver** [comment]
The PDF uses the wrong font, sorry!

**Comment by hjoliver** [comment]
The correct one is a Google Font - Titillium Web.  I guess I should dig up, or recreate, the "official" logo SVG.

**Comment by kinow** [comment]
I was going to ask exactly for a SVG of the Cylc logo, so that I could just adjust the colour/tone. If you have one, that would be helpful, please. Otherwise I can try to recreate it in Inkscape.

**Comment by hjoliver** [comment]
Let me have a look ...

**Comment by hjoliver** [comment]
Hmmm. Now I recall the reason I don't have a proper SVG version: I couldn't figure out how to use Google Web Fonts in Inkscape.  (So I have an SVG of the circular blobs, but the cylc logos with text were always screenshot PNG from browser, I think).  Any suggestion on how to do this?

**Comment by kinow** [comment]
I think the easiest way is [download the font](https://fonts.google.com/specimen/Titillium+Web?selection.family=Titillium+Web), unzip the files somewhere, then copy to `~/.fonts/$NAME_OF_FONT`.

Then refresh your linux font cache with something like `sudo fc-cache -f -v`. You should see the new font directory appear in the console. Open (or close first) Inkscape, and the font should be available.

**Comment by kinow** [comment]
(to download a font, click the font you'd like in Google Fonts, then choose "Select This", click on the icon that should then appear near the bottom right, a panel will come up... in this panel, there will be an icon in the top right corner to Download the file...)

**Comment by hjoliver** [comment]
Ah yes, that works thanks - the download link was a little hard to find.

**Comment by hjoliver** [comment]
(In fact now I do recall doing this several years ago ... but I still don't seem to have an SVG of the full logo, so will recreate it).

**Comment by hjoliver** [comment]
(Done, will upload the SVG later...)

**Comment by kinow** [comment]
Thanks @hjoliver !

**Comment by hjoliver** [comment]
(SVGs posted to Riot, until we agree on where to store them)
