### ISSUE TITLE
Easy access key to icons

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-ui#1210]
We already have a key in the quick-start guide, but as an end user I think I would like a tooltip key somewhere in the page (bottom left?), or perhaps one each for task and job states. Hovering over this key would pop up a quick reminder.

Is this a good idea?

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
We need to raise the visibility (and improve the content of) the guide.

Not convinced we need other systems for signposting the same thing.

**Comment by oliver-sanders** [comment]
IMO close this issue in favour of a better advertised guide.

We can't integrate documentation into every single corner of the UI, the result would be too cluttered. Take a look at the GitHub app for example, where's the docs?

**Comment by hjoliver** [comment]
> Take a look at the GitHub app for example, where's the docs?

GitHub's UI is very wordy, but it does provide tooltips for un-labeled icons:

![sshot](https://github.com/cylc/cylc-ui/assets/2362137/134e472d-2630-4a57-9069-f6e3ff06addf)

It might be worth us doing the same. E.g. if you hover over a failed task icon, it could say "failed task".

**Comment by oliver-sanders** [comment]
Note if you click on a failed task icon, it says "failed task".

**Comment by hjoliver** [comment]
I think I just got owned 😬
