### ISSUE TITLE
tree: missing tasks

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1219]
A bug has been reported where a task was missing from the tree view but present in the table and graph views.

The graph was simple:

```
a => b
```

Where "a" had succeeded but "b" had failed.

Only "a" showed in the tree view.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
I failed to reproduce this with a simple `R1 = "a => b"` test using current cylc-flow and cylc-uiserver master versions, in normal and back-compat mode.  I take it you have no info on versions, any manual interventions, etc.?

**Comment by oliver-sanders** [comment]
* Version was Cylc 8.1.0, UI 1.4.0.
* I don't expect there were any manual interventions but canot confirm.
