### ISSUE TITLE
Task filtering in tree and table view raising TypeError

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-ui#1220]
**Describe the bug**

Task filtering is broken for me in tree and table view on master branch. I get `TypeError: node.name is undefined`. 

![image](https://user-images.githubusercontent.com/37735232/214583373-29a021ed-cc2c-4d37-873e-836bd5ca77c4.png)

Can anyone confirm before I have a go at fixing?

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
I can reproduce but get a slightly different error. But my error is fixed by #1182. May be worth getting a maintenance release out? @oliver-sanders

**Comment by oliver-sanders** [comment]
> Task filtering is broken for me in tree and table view on master branch

Was working for me on the release the other day so a recent change?

> node.name is undefined

`node.name` should always be defined, so I think this means `node` is undefined?

> worth getting a maintenance release out

Yup.

**Comment by datamel** [comment]
Strange you get a different error. 
I get this in the console log: 

![image](https://user-images.githubusercontent.com/37735232/214601209-d14364d0-108b-41b1-ac06-663637397397.png)

Possibly introduced with this pr: https://github.com/cylc/cylc-ui/pull/1123

**Comment by MetRonnie** [comment]
I have checked out 1.4.0 and can still reproduce my version of the error
