### ISSUE TITLE
workspace: avoid importing views until needed

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1221]
We currently import all of the views into the workspace component.

I think this means the resources required for *all* of the views are loaded when you open the workspace component irrespective of whether you need them or not. **Needs confirmation**.

It was an ok approach to start with, but as the list of views grows this will cause loading pain. It is possible to dynamically import components in Vue something like:

```js
components: {
  TreeView: () => import('...'),
  ...
}
```

This will, however, require moving the view metadata (title and icon) outside of the view component so that it can be imported separately e.g something like:

```js
export treeViewMetadata = {
}

export default {
  ...
}
```

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
Can this be bumped to 1.6.0, as we are aiming to release 1.5.0 soon with important bugfix #1182 ?

**Comment by MetRonnie** [comment]
Useful article: https://vuedose.tips/dynamic-imports-in-vue-js-for-better-performance

I think this is best done after the Vue 3 upgrade as it will conflict otherwise. Also an extra thing is needed in Vue 3: https://stackoverflow.com/a/68568767/3217306
