### ISSUE TITLE
Avoid creating unnecessary reactive variables

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#1247]
**Describe exactly what you would like to see in an upcoming release**

Every element in `data` is made reactive. That creates unnecessary [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) objects in Vue. While the performance improvement won't be much, I guess if you have a large workflow every nano/micro second of processing, and every scrap of memory matters, and since it's a cheap fix…

Here's an example: https://github.com/cylc/cylc-ui/blob/2907d64656181ba95e2693c98a7b4de5b8ebcbc3/src/views/Log.vue#L140-L146

I believe that list of files is static and not meant to be changed in the UI, so it can be replaced by `jobLogFiles: Object.freeze(['job.out',`, or moved outside as a constant somewhere :+1: 

**Additional context**

I saw a post on Discourse and checked out the code to play with the old workflow `five`, and while having a look at the code I noticed that list. Since I had just changed that in Jena UI's code, I started freezing some `data` properties but never finished to get a good pull request. Thus this PR :grimacing: :wave: 

Some other good tips to improve performance: https://old.reddit.com/r/vuejs/comments/10piox0/what_vue_specific_performance_tips_do_you_have/j6lm3f4/

(Great job on the graph & log views! They are fun!)

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
I have been moving unnecessarily reactive data properties out into custom options as I have gone along. E.g. https://github.com/cylc/cylc-ui/pull/1218/files#r1081292026
