### ISSUE TITLE
Log view usability improvements

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1251]
- [x] Long workflow ID overflows input

  ![image](https://user-images.githubusercontent.com/61982285/220713526-811a77bb-17c9-4c5f-bfea-ea932d3bb3b7.png)

  If required the inputs should wrap onto the next line

- [x] Use a skeleton loader or indeterminate progress bar to indicate when log is loading. When viewing remote logs it can be quite a while before anything shows up.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Closed by #1275
