### ISSUE TITLE
Investigate running npm run serve with jupyterhub

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#126]
Investigate developing on the fly with live data.

At the moment I run

- `jupyterhub`
- `npm run build:watch`
- `cylc run --no-detach --hold five`

We could replace the second command by `npm run serve`, so that the browser is refreshed whenever we change the code, with the live data.

**Comment by kinow** [comment]
See https://github.com/cylc/cylc-ui/issues/126 for a PR that had a tentative fix for it with the `devServer` npm/node proxy. There may have other alternatives.

Some notes:

- `/graphql` is protected, so users must authenticate against the hub first to get a valid cookie
- running `jupyterhub` is not enough, as we need `cylc-uiserver` which only initiates on the first request to `http://localhost:8000` or when manually clicking on the "Launch" button in the hub
- `/userprofile/` is used when the application is loaded to obtain the user information (used in other parts of the app), so that also needs to be redirected.

**Comment by hjoliver** [comment]
Is the only advantage of this that you get instant update after code changes, without doing a reload?  If so, I wonder if it's worth the effort?  (Reloading a page manually is not very difficult :grin: ).

**Comment by kinow** [comment]
> Is the only advantage of this that you get instant update after code changes, without doing a reload? If so, I wonder if it's worth the effort? (Reloading a page manually is not very difficult 😁 ).

I think so. I was implementing it, but wasn't really going to use it (I think I created this issue after a meeting, or some comments from Riot).

I use `npm run serve` only with the offline mode, when changing HTML/JS code for the design layout, like creating components. And `npm run build:watch` + `jupyterhub` for all other cases, with PyCharm and WebStorm open ready to connect the debugger to Py or JS code that is running.

**Comment by hjoliver** [comment]
Seems sensible to me, given the complications you've raised (auth etc.) and the seemingly marginal benefits.  @oliver-sanders - do you agree to deprioritize or close this issue? (Asking as I think you were one of the original proponents of doing this?).

**Comment by oliver-sanders** [comment]
> And npm run build:watch + jupyterhub for all other cases

I've not had the chance to work on cylc-ui for a while so I haven't actually used `build:watch` yet.

> Is the only advantage of this that you get instant update after code changes, without doing a reload?

The motive was that you didn't have to rebuild the entire project every time you make a code change (as it takes quite a long time). If `build:watch` does incremental builds the same way `serve` does then that should be sufficient to close this issue.

**Comment by kinow** [comment]
>The motive was that you didn't have to rebuild the entire project every time you make a code change (as it takes quite a long time).

Ah, I thought the motive was actually get the websockets update from `npm run serve` but using live data.

`npm run serve` will use Node.js http server to serve the current project, also reloading the browser whenever the project changes/rebuilds.

> If build:watch does incremental builds the same way serve does then that should be sufficient to close this issue.

Yup, it does. It will first build the project, and then start to watch for changes. If you change a file that is expected to change the project (some files are ignored like test coverage settings, etc) it will re-build the project for you.

Only difference is that it does not serve the files. So you must have `jupyterhub` serving it, or start a `python -m http.server 8000`, or try to open in the browser with `file://.../index.html` though I don't think it will work.

If you are running it behind `jupyterhub`, the JS code will be updated automatically, but you still need to refresh the browser (which you don't need with `npm run serve`; that's why I use `npm run serve` when creating components as that's the fastest way for me, with the mocked data).

**Comment by oliver-sanders** [comment]
> Only difference is that it does not serve the files

That's fine, spinning up the Jupyterhub Tornado server is no biggie.

**Comment by oliver-sanders** [comment]
Thanks for your work on this!
