### ISSUE TITLE
Graph view: group tasks by cycle point

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-ui#1280]
hi there,

just wondering if it would be possible to group tasks by cycle point as was possible in `cylc` 7 and as the shown by `cylc graph -c WORKFLOW` in  `cylc` 8 (see screenshot).

cheers,

jonny

![image](https://user-images.githubusercontent.com/12940715/233817686-d16b3b05-3dc6-47b9-8fd9-e8bc3a712c86.png)

**Comment by jonnyhtw** [comment]
ah cool, thanks. 😄

**Comment by oliver-sanders** [comment]
(will leave this issue open to remind us)
