### ISSUE TITLE
dynamic updating of graph view window extent?

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-ui#1281]
hi there,

currently it's only possible to change the graph window extent (see screenshot) when the graph view itself changes, i think when a new task is triggered or a running one changes?

is it possible to make this happen as soon as requested rather than have to wait for the currently-visible graph view to change?

thanks!

jonny

![image](https://user-images.githubusercontent.com/12940715/234250934-fd5a1e62-7761-4633-bc9c-1cdb2da0c68b.png)

**Comment by oliver-sanders** [comment]
Not at the moment.

Manually setting the graph window extent will become more of a core feature in the future with a dropdown box to set it more conveniently.

**Comment by jonnyhtw** [comment]
> Not at the moment.
> 
> Manually setting the graph window extent will become more of a core feature in the future with a dropdown box to set it more conveniently.
> 
> The algorithm will need to be refined before we push this feature. In the mean time be aware that increasing the window causes extra CPU load on the scheduler so use with caution.

OK all sounds good to me. climate workflows are usually (relatively) small so presumably won't be much of an issue. will use with caution though as you say! 😄 

thanks

**Comment by oliver-sanders** [comment]
As of the upcoming cylc-flow 8.3.0 the graph window should update immediately (rather than on the next graph change).

The remainder of this issue (making the n-window easier to configure) is covered by https://github.com/cylc/cylc-ui/issues/864
