### ISSUE TITLE
log: enable word wrapping

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-ui#1285]
Hey, 

Would it be possible to enable line wrapping in the `job*` file output? For some reason there are often extremely long lines in output from the models I run (see screenshot). Just wondering. 

Cheers,

Jonny

![image](https://user-images.githubusercontent.com/12940715/235004178-59d9f230-dcb2-4415-9497-f50103572d94.png)

**Comment by oliver-sanders** [comment]
Log files are currently displayed as a plain code-block.

We plan to use a code-viewer such as CodeMirror to display these files in the near future. Hopefully, the viewer we pick will provide functionalities like line-wrapping, syntax highlighting, line numbers and more.

It's a little tricky as our logs are dynamic (new lines are constantly being loaded) so will require investigation.

Related to #1208, #1205
