### ISSUE TITLE
Tree view not showing the same tasks as graph and table views.

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-ui#1291]
Hi there, 

As shown in the attached screenshots in one of my workflows at version `8.1.4`, the tree view is not showing all the tasks which are visible in the graph and table views. 

The missing tasks in the tree view are:

1. `atmos_crun.18500101T0000Z`
2. `rose_ana_crun.18500101T0000Z`
3. `atmos_crun.18500601T0000Z`

I've discussed this with @hjoliver so opening issue to start looking into this.

Cheers, 

 

![image](https://github.com/cylc/cylc-ui/assets/12940715/38c7d311-a564-41fc-92e5-d32735ebd20b)
![image](https://github.com/cylc/cylc-ui/assets/12940715/7eb80a06-0e84-42e3-8f4f-043074ead9d0)

**Comment by hjoliver** [comment]
Thanks for the bug report @jonnyhtw !

Other details from our discussion:

- this is 8.1.4

With the workflow still running in the state shown above:

- reloading the GUI in the browser did not fix the tree view
- killing and restarting the UI Server did not fix it either

**Comment by oliver-sanders** [comment]
Unfortunately we're going to need a reproducible example to investigate.

Can you repeat this? If so what did you do to make it happen? Were there any interventions leading up to the issue e.g. reloads?

**Comment by hjoliver** [comment]
> Can you repeat this?

I'm going to try running @jonnyhtw 's workflow tomorrow to see if I can make it happen.

>  Were there any interventions leading up to the issue e.g. reloads?

That I'm aware of, there were a bunch of reloads to change the platform assigned to the `rose_ana_crun` task, after each of which that (failing) task was retriggered.

**Comment by hjoliver** [comment]
(And the workflow does have a fairly complicated inheritance hierarchy).

**Comment by oliver-sanders** [comment]
To help with debugging...

The UI data store maintains a "family tree" to hold inheritance information. From "cycle" down, the tree view runs off of the "family tree" whereas the tree view uses the regular tree.

Here's the point where the Tree view branches off to follow the family tree:

https://github.com/cylc/cylc-ui/blob/8cf019c68ab85904f342c3d8c7cb8b9087459f43/src/components/cylc/tree/TreeItem.vue#L43-L48

And here's where the family tree is generated:

https://github.com/cylc/cylc-ui/blob/8cf019c68ab85904f342c3d8c7cb8b9087459f43/src/store/workflows.module.js#L346-L377

To inspect the data store, open up the Vue devtools, navigate to the VueX tab and drill down the cylcTree to find the relevant tree.

**Comment by jonnyhtw** [comment]
> Would be good to confirm the UI / UIServer version too

hi @MetRonnie, the UI version is Cylc UI 1.4.0. 

cheers, 

jonny

**Comment by jonnyhtw** [comment]
> > Can you repeat this?
> 
> I'm going to try running @jonnyhtw 's workflow tomorrow to see if I can make it happen.
> 
> > Were there any interventions leading up to the issue e.g. reloads?
> 
> That I'm aware of, there were a bunch of reloads to change the platform assigned to the `rose_ana_crun` task, after each of which that (failing) task was retriggered.

can confirm that exactly the same thing happens after starting again from scratch. 

cheers,

**Comment by jonnyhtw** [comment]
after working with @hjoliver we worked out that the problem was something to do with the presence of a `~/.local` directory was messing things up. 

removing this has fixed this problem.

cheers,
