### ISSUE TITLE
Table view: order of jobs wrong

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-ui#1292]
Hi there, 

I'm using version `8.1.4` and have needed to change the `platform` that a particular task runs on whilst the workflow is running. However, the UI does not report the latest submit number's `platform` correctly but shows the one from submit `#1`.

In the screenshot `#1` was run on `maui-ancil-slurm` and `#2` on `localhost` but the top, unexpanded view still shows the `platform` from `#1`.

In the event that this isn't too onerous a task for a relative noob to fix then I'm happy to try and open a pull request myself.

Cheers, 

Jonny

![Screenshot 2023-05-11 175547](https://github.com/cylc/cylc-ui/assets/12940715/48d40838-220c-45e5-82e7-a87ffffa829a)

**Comment by hjoliver** [comment]
It looks like the "unexpanded" line is showing the oldest job rather than the newest one.

**Comment by hjoliver** [comment]
I presume this is a UI issue, in which case probably a quick fix.

**Comment by hjoliver** [comment]
(This bug made it look as if the reload wasn't working, but it turned out to be just a UI display issue).

**Comment by jonnyhtw** [comment]
> I presume this is a UI issue, in which case probably a quick fix.

ok cool, i'll clone the repo and will take a butchers

**Comment by hjoliver** [comment]
Forewarning - it ain't Python!

**Comment by MetRonnie** [comment]
I've got a fix for this, will come after #1269
