### ISSUE TITLE
(Webkit) Graph view: clock-face progress indicator missing

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1293]
> I spotted one issue where the clock-face progress indicator doesn't show in the graph view:
>
> <img width="722" alt="Screenshot 2023-04-26 at 15 20 57" src="https://user-images.githubusercontent.com/16705946/234606579-aa4e228d-9b5b-438f-a70b-a62b79099eb1.png">
>
> I think this was working before [Vue 3] but I remember there was some difference between Safari/others regards SVG rotation-centre coordinates. Working on other browsers?

_Originally posted by @oliver-sanders in https://github.com/cylc/cylc-ui/issues/1269#issuecomment-1523517643_

Moved to its own issue to avoid getting lost in the collapsed history

**Comment by hjoliver** [comment]
This is Safari only?

**Comment by oliver-sanders** [comment]
WebKit is the rendering engine used by Safari and some others on MacOS and all browsers on iOS (incl Chrome).

**Comment by MetRonnie** [comment]
Was this fixed by #1780?

**Comment by oliver-sanders** [comment]
I think I tested this with Safari, but I can't confirm it.

**Comment by oliver-sanders** [comment]
Working well on Safari!

![Kapture 2024-08-15 at 19 23 40](https://github.com/user-attachments/assets/b67710ad-8b7f-4747-a9a5-6793ebc828ba)
