### ISSUE TITLE
This file has been truncated because it is over 5000 lines long.

### ISSUE THREAD

**Issue by ejhyer** [cylc/cylc-ui#1294]
### Problem

This 5000-line limit is too low-- some jobs just make a lot of output!

### Proposed Solution

Identify where this limit is set, or make it configurable.

**Comment by hjoliver** [comment]
Thanks @ejhyer. We agree, but it's not entirely clear how best to dynamically stream huge job logs to a web UI. It is one of the things on the team's ToDo list. I'm not entirely sure which is the related Issue, so will leave this up for now.
