### ISSUE TITLE
Subscriptions: tasks might not receive updates at stall or when a new view is added?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1346]
### Description

This is probably actually a cylc-flow issue but until we have figured it out it may as well go here. Somewhat related to https://github.com/cylc/cylc-flow/issues/5598 

May be the same issue as https://cylc.discourse.group/t/previously-completed-task-not-disappearing-from-workflow/672?

A task (`c_x3`) has been left in the running state in the UI after a stall when it has actually succeeded.

Also the graph view does not show a link between `b_x3 => c_x3`.

![image](https://github.com/cylc/cylc-ui/assets/61982285/09846b3c-f186-488a-afbc-df72b0567d6f)

### Reproducible Example

```ini
[scheduler]
    allow implicit tasks = True
[task parameters]
    x = 1..4
[scheduling]
    [[graph]]
        R1 = a<x> => b<x> => c<x>
[runtime]
    [[B,C]]
    [[b<x>]]
        inherit = B
    [[b<x=1>]]
        script = sleep 1; false
    [[c<x>]]
        inherit = C
```

### Additional context

Running a query at this point only shows the expected `_x1` set of tasks.
```
query {
  taskProxies {
    id
    state
    prerequisites {
      expression
      satisfied
    }
  }
}
```

**Comment by MetRonnie** [comment]
Update: it seems to be the case when adding a new view near the point of stall? I have managed to reproduce a couple of times by adding a table and graph view at around that point

**Comment by oliver-sanders** [comment]
Are we sure this is related to adding new views?

**Comment by MetRonnie** [comment]
Closing as not reproduced for a while
