### ISSUE TITLE
context menus

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#138]
Implement context menus (should work on mobile).

With a bit of styling the MDI context menu might suffice.

Features:

* Optional text header
  * e.g. for showing job information
* Optional description line for each item
* Optional short-cuts to common functionality
  * e.g. view the job.out or job.err.
* Special icons where needed.
  * The icons in the sketch bellow were quickly knocked-together, can easily refine them and export as SVG icons.

![right-click-menus](https://user-images.githubusercontent.com/16705946/61529573-927bc500-aa19-11e9-9e19-8d6800e9ff28.png)

Examples of context menus:

![context](https://user-images.githubusercontent.com/16705946/70873199-7fddda00-2011-11ea-9caa-b52b71f7b563.png)

**Comment by matthewrmshin** [comment]
Should `reset` and `remove` hide under an advanced section of the menu?

**Comment by oliver-sanders** [comment]
Originally I thought so but as there are so few items in the menu anyway.

Options:

* Put an ellipsis (...) button or similar at the bottom of the menu which the user can click to reveal the hidden options.
* Put these options after a divider in a "danger zone".

**Comment by matthewrmshin** [comment]
Another option is to have the normal click bring out a box that displays the meta data of the task. The box can have a button to view more info such as prerequisites and outputs, and buttons to trigger, hold, release, reset, remove, insert a predecessor/successor, etc.
