### ISSUE TITLE
Avoid duplication in page view title

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#142]
Currently the title displayed is calculated in the View, under 

```
  metaInfo () {
    return {
      title: 'Cylc UI | User Profile'
    }
  }
```

The title could have its root (Cylc UI |) calculated elsewhere, then the View title could be appended to it.

This way if we rename Cylc UI to something else, we don't need to update N places (N = number of views with metaInfo titles)

Low priority.

**Comment by hjoliver** [comment]
> This way if we rename Cylc UI to something else,...

It seems unlikely that we'd do that, but you never know... :grin:

**Comment by matthewrmshin** [comment]
You never know when you may decide to rebrand it to CylcUI or cylcui or cylc-ui or just Cylc. 😈

**Comment by kinow** [comment]
It's just because I remember first calling it "Cylc Web", then when it was renamed, I had to update it in more than two places, and made a mental note to fix that some day. Then just came by the metaInfo title today while working on another issue :)

**Comment by kinow** [comment]
Hmm, the title is set by Vuetify. The framework has some code that reads that `metaInfo` part. I started working on a solution that would use Vuex to store the root part of the title, but feels wrong to use Vuex for that. I think ideally we would have a simpler solution, that is also easier to maintain.
