### ISSUE TITLE
header: use LocalStorage for owner and deployment values

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1457]
See https://github.com/cylc/cylc-ui/pull/1444#discussion_r1311534802

We should also include a remove button to allow typos to be removed.

**Comment by markgrahamdawson** [comment]
With regards to a remove button Ill pop it on the side (any preference as to which?) Should it clear the whole local storage variable (the whole list of server owners/deployments) or just the server owner/deployment that is currently selected @MetRonnie @oliver-sanders.

![image](https://github.com/cylc/cylc-ui/assets/7523921/086558d3-b743-43ad-b5ff-8d6b0678007b)

**Comment by MetRonnie** [comment]
I think it would make sense to have "x" buttons after each username (in the `append-item` slot - see https://vuetifyjs.com/en/api/v-select/#slots-append-item)

**Comment by oliver-sanders** [comment]
> I'm guessing we don't want to give the user the option to delete their name under 'server owner' or the default domain...

Good thinking.
