### ISSUE TITLE
TypeError during pruning causes tasks to be left behind as running when they have actually succeeded

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1470]
### Description

A user has reported a problem that reliably occurs where tasks that have succeeded get left behind as running in the table and graph views, but not the tree view which shows everything correctly. This only seems to occur after the GUI has been left open with the workflow running overnight.

There is nothing special about the workflow itself.

I have tracked the `TypeError` down to this line in the workflows module function `remove()`:
https://github.com/cylc/cylc-ui/blob/c151c9a8084e48cc07b664e0188c62665c675016/src/store/workflows.module.js#L485

where `firstParent` is undefined.

Additionally, the arrows may disappear from the graph view, which I have tracked down to the `layout()` method:
https://github.com/cylc/cylc-ui/blob/c151c9a8084e48cc07b664e0188c62665c675016/src/views/Graph.vue#L652-L659

where `bbox` is undefined.

**Comment by oliver-sanders** [comment]
@MetRonnie is the Graph error you posted associated with the firstParent.id error?

**Comment by MetRonnie** [comment]
Don't know, but a user reported getting both in one workflow run

**Comment by kinow** [comment]
I came here to see looking for a similar error to what I had preparing some slides for a presentation this week.

I had a simple workflow and three views open, tree, table, graph. Once the workflow finished (a few minutes), every view was empty but the graph view.

I closed the tabs and reopened and the graph was empty. I will try to reproduce again tomorrow and share the workflow here and check if I got the TypeError too 👍

**Comment by oliver-sanders** [comment]
> every view was empty but the graph view.

That's actually kinda intentional. The graph view will never fully empty because the SVG pan-zoom library we use can't handle an empty document. I'll try and put in some sort of placeholder to prevent this from happening.

**Comment by oliver-sanders** [comment]
I think #1513 should resolve the bulk of the errors I've been seeing.

**Comment by MetRonnie** [comment]
I seem to easily reproduce this by closing all lumino tabs and then adding the graph view for a running workflow. Seems to be fixed by #1513
