### ISSUE TITLE
Logo not working on Chrome

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#148]
Synced the code, and started the test server this morning, launching on Firefox and Chrome, but the logo was not displayed on Chrome.

Not sure if due to some update... I am quite sure I used Chrome before since we changed the logo to use SVG.

**Comment by kinow** [comment]
Hmmm. Just tested from home, and Ffox is fine, Chrome is not showing the logo. Might need to use that approach you mentioned the other day @oliver-sanders, or embedding the SVG in a - I think - object tag?

**Comment by oliver-sanders** [comment]
I think it would be best to put the SVG logo in a file for easy re-use. Just stick it in an `<img>` tag, support is pretty universal these days (I have tested this approach with chrome for another project).

**However** directly embedded SVG should work fine so I'm curious that it doesn't!
* Do the task/job icons show up fine (they are embedded in the same manner)?
* Just a hunch, try suspending addblock.

**Comment by kinow** [comment]
Disabled adblock (uBlock origin, icon after the address search input greyed-out), still same issue. Task and Job icons appear to work fine, at least similar to what I see on Firefox.

![image](https://user-images.githubusercontent.com/304786/62089641-db573780-b2bd-11e9-9c88-1c27e3bb0fd6.png)

But these were good suggestions. Will try using the `<img>` approach now.
