### ISSUE TITLE
Filtering by waiting tasks in GScan doesn't work

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1537]
No workflows show when filtering by waiting tasks, even though there _are_ waiting tasks. This bug affects the offline mode and the production build

![image](https://github.com/cylc/cylc-ui/assets/61982285/24ee9b56-0941-4e37-b68a-20c0042e2e1a)

**Comment by oliver-sanders** [comment]
This will never work because the state totals are actually listing job states not task states.

The "waiting" state should not be an option for filtering workflows.

**Comment by MetRonnie** [comment]
In #1549 I corrected the source of the states GScan was looking at from jobs -> tasks

**Comment by oliver-sanders** [comment]
Apologies, state-totals are task states, mb.
