### ISSUE TITLE
edit-runtime textboxes do not understand up/down arrow keys

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-ui#1610]
### Description

When editing a textarea in the UI Server Edit Runtime area, the up and down arrow keys do not navigate through the text, only left and right.

### Reproducible Example

1. In the UI Server, right click on a task and do "Edit Runtime"
1. Click into any textarea that has multiple lines in it
2. Press up and down arrow keys to navigate around
3. See if the cursor moves at all (it does not for me or another person I asked to test, both using Firefox I think).

### Expected Behaviour

Up and down arrow keys should navigate through the textarea.

**Comment by oliver-sanders** [comment]
E.G. if the cursor is on the middle line (`_`) in this example, pressing down does nothing and pressing up jumps to the bottom of the form.

![Screenshot from 2024-01-02 12-58-10](https://github.com/cylc/cylc-ui/assets/16705946/ad2b66d8-565d-49b4-b78b-74b20d65841d)

Tab and shift+tab work correctly for moving between inputs, but up/down don't work for moving the cursor within inputs.
