### ISSUE TITLE
Minor cosmetic bug - menu doesn't disappear when a form opens

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-ui#1654]
### Description

Minor cosmetic bug. Only tested in Firefox. When you select an option which pops up a form, the dropdown menu remains visible behind the form until you click in the form, then it disappears.

![image](https://github.com/cylc/cylc-ui/assets/15375218/13927f5e-fde7-474d-8138-662e716e200f)

### Reproducible Example

1. Open a workflow in the UI
2. Click the top accordian button to show the menu
3. Click on any of the pencil icons for the menu options
4. Notice the menu remains visible behind the form
5. Click in the form
6. Notice the menu has now disappeared

### Expected Behaviour

Menu should collapse as form opens.

**Comment by oliver-sanders** [comment]
This is intended, it allows you to cancel the command you're editing and return to the menu.

If you submit the command the menu will close afterwards.
