### ISSUE TITLE
Menu button and forms - what should be happening?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-ui#1659]
### Description

Following on from https://github.com/cylc/cylc-ui/issues/1654

In that Issue, @oliver-sanders said that the menu not disappearing when you start a form is intentional, so that if you click cancel, it will return back to the menu.

> This is intended, it allows you to cancel the command you're editing and return to the menu.

This does not happen. If I click cancel, the menu disappears. 

### Reproducible Example

Windows, Firefox (only environment I have tested on).

1. In a workflow, click on the top level menu button
2. Click the Pencil to open a form
3. Notice menu is there behind the form
4. Click Cancel
5. Notice form AND menu disappear

### Expected Behaviour

Either

1. Open a form, the menu disappears

OR

2. Open a form, menu remains, click cancel, menu stays up

**Comment by oliver-sanders** [comment]
Working as intended v2.3.0 - development:

![vokoscreen-2024-02-02_09-27-02](https://github.com/cylc/cylc-ui/assets/16705946/8e8a0425-4d5e-4f8a-8f36-91e0cf11c966)

**Comment by MetRonnie** [comment]
Closed by https://github.com/cylc/cylc-ui/pull/1642
