### ISSUE TITLE
task icons: failed & submit-failed too similar?

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-ui#173]
(Sorry to bring this up now after the icon implementation, but this is the first time I have noticed this, & better to raise it sooner rather than later when it could be more deep-rooted into the overall UI design.)

The task icons for 'failed' & 'submit-failed' as implemented, but still (though less notably) in the design mock-up, are barely distinguishable. Even upon zooming in so they are much larger than would be practicable for the viewing of realistically-sized suites by task, it is difficult to tell them apart:

![scr-failed-states](https://user-images.githubusercontent.com/30274190/62781343-ac0bac00-baaf-11e9-9f61-a9c4030c175e.png)

At 100% zoom the perceptible difference becomes negligible.

I appreciate it is intentional that the two look similar, given they are both states of a variant of task failure, but I think they still need to be discernible at standard size. Can we make a change to one or both to accomplish this?

The natural approach would be to increase the size of the inner circle for the 'submit-failed' icon, but even then I am not convinced it would be distinct enough. I would personally like to change the nature of the 'submit-failed' icon to be different in some other way, by not using the dot & instead for example:

* rotating the ``x`` cross 45 degrees to a plus-style cross (``+``); or
* adding a few lines to make an hourglass-like symbol, like [this](https://en.wikipedia.org/wiki/Extinction_symbol#/media/File:Extinction_Symbol.svg); or
* making the ``x`` cross legs much shorter, & to contrast make them fill out all the way to the outer circle for the 'failed' icon.

**Comment by hjoliver** [comment]
@sadielbartholomew - I agree they are hard to distinguish.

If the "X" is a cross to indicate failure on top of the under-lying icon, it doesn't seem right to me to have a different kind of cross for two cases. The difference should be in the underlying icon - which shows what failed, submission or execution.

If that reasoning is sound, the current design for execution-failed actually looks like waiting-failed, because it is a cross on an empty circle.  

So how about we put a cross on a running icon, something like this (inferior inkscape skills :grimacing: ):

![bitmap](https://user-images.githubusercontent.com/2362137/62999296-106ca800-bec2-11e9-8efe-6c806cbef057.png)

Maybe we could even show how far through the task got before it failed...

**Comment by hjoliver** [comment]
Off-topic, but should we rationalize these task state names:

| old | new |
|---|----|
| submitted | submitted |
| running | executing |
| submit-failed | submit-failed |
| failed | execution-failed |

**Comment by matthewrmshin** [comment]
> Off-topic, but should we rationalize these task state names:

We may want to also consider task message/triggers/outputs. E.g. we have the *:start* trigger in graph, and the *started* message that takes us to the *running* state.

**Comment by oliver-sanders** [comment]
> task icons: failed & submit-failed too similar

This was kinda on-purpose. For the following reason:

> it doesn't seem right to me to have a different kind of cross for the two cases

But I actually quite like Hillary's suggestion, it makes it clear that a failed job is also a completed job.

**Comment by sadielbartholomew** [comment]
> So how about we put a cross on a running icon, something like this

Great idea! Yes, I really like that suggestion, because of your reasoning RE 'waiting-failed', & also since as stated more useful information would be incorporated, & actually the progress through the task at point of execution failure could be really useful to users.

Also, with your suggestions as sketched @hjoliver, for the most common flows through task states (ignoring any retries) of:

* 'waiting (-> submitted) -> submit-failed';
* 'waiting -> submitted -> running -> failed';
* 'waiting -> submitted -> running -> succeeded'

the icons would contain all elements from icons before them in those sequences, but with some new aspect added successively (or overlayed in the case of 'succeeded').

**Comment by sadielbartholomew** [comment]
> Off-topic, but should we rationalize these task state names:

I certainly think 'failed' being clarified as 'execution-failed' would be a clearer terminology, as at the moment 'failed' by name implies it could include failures in submission. Then 'running' to 'executing' makes sense to be more consistent with that. 'submit-' to 'submission-' would also be consistent with 'execution-', unless we go for 'submit-failed' & with 'execute-failed' for harmony on that aspect, but I prefer the former pair.

So I like all of those suggestions too!

**Comment by hjoliver** [comment]
> > Off-topic, but should we rationalize these task state names:
> 
> We may want to also consider task message/triggers/outputs. E.g. we have the _:start_ trigger in graph, and the _started_ message that takes us to the _running_ state.

https://github.com/cylc/cylc-admin/pull/47
