### ISSUE TITLE
Move services to within Vuex stores

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#174]
Normally in apps using Vuex, the pattern is

- Views/components use Vuex state/getters to access data
- Views/components use Vuex actions to dispatch asynchronous actions
- Vuex asynchronous actions may then call Axios/GraphQL/etc and finally commit mutations

When we started Cylc UI, while writing the first unit tests, and thinking about mocking the networking layer, I added services to communicate with Axios and later with GraphQL.

This allowed us to have the `offline` mode with mocked services, as well as easily create mocks in unit tests. The cost was the awkwardness of having Vue.js Views/components accessing Vuex for data retrieval, but services directly.

Today while reading another Vue.js code base I realized they had actually done a better job. They moved the code from Axios into some `./api/index.js` file. And imported that into the Vuex store actions.

If we copy that behaviour, the code structure will be easier to understand. The whole development of components will be against the local `data`/`computed`, and `Vuex`. And `Vuex` only will be accessing the services (which may be mocked when testing or running under the `offline` mode).

**Comment by matthewrmshin** [comment]
Sounds like a good plan, if I understand what you are saying correctly.

**Comment by kinow** [comment]
>Sounds like a good plan, if I understand what you are saying correctly.

The picture from [this article](https://medium.com/@cyphertree_dev/data-flow-in-vuejs-vuex-application-112383d1a3ed) gives a good idea of what it normally look like:

![0*5371HsfGz_efVuSV](https://user-images.githubusercontent.com/304786/62853649-2141e000-bd41-11e9-8532-cb7084dd5be8.png)

In our case, between Component and Action, we have a Service. But what I only realized later, is that we could moved the Service to the Action, as Vuex actions are asynchronous, so it is Ok to have REST/GraphQL/etc calls there (while it's not a good idea to have in a synchronous mutation).

**Comment by kinow** [comment]
I think that's not easy to achieve. The views are not calling functions that could be simply moved to Vuex anymore.

Most views now subscribe and register via the `WorkflowService`. Moving those methods to Vuex would make things more complicated for new developers familiar with Vue.js, rather than make it more familiar.
