### ISSUE TITLE
Organize releases in this repository

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#175]
I was keeping track of the changes in the beginning of the project with some tags, to be able to go back in time after some complicated changes. I think these old tags can now be removed.

This is also going to be helpful on https://github.com/cylc/cylc-admin/issues/27. Not sure whether we should start on 0.1, or 1.0, or use alpha/beta, etc.

**Comment by matthewrmshin** [comment]
I vote for 0.1.

**Comment by kinow** [comment]
In [yesterday's meeting](https://cylc.github.io/cylc-admin/meetings/vc-9-sep-2019-agenda.html) we decided to go semver for each component, starting at 0.1.

I will delete my old releases, and update the package.json if necessary.

**Comment by hjoliver** [comment]
Same with cylc-uiserver :+1:

**Comment by kinow** [comment]
Also created milestone: https://github.com/cylc/cylc-ui/milestones?with_issues=no
