### ISSUE TITLE
Spurious text in job log drop-down menu

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#1806]
Screenshot from a NIWA user:

![image](https://github.com/cylc/cylc-ui/assets/2362137/7e7f5926-00c3-4acd-adf6-07ec6f57511c)

The text appears to be svn output, in the job.out file. 

I have not managed to reproduce the error myself yet.

**Comment by oliver-sanders** [comment]
To list log files the UIS uses `cylc cat -m list-dir`, presumably something involved in this request (ssh, bash, profile files) is writing to stdout and that is getting dragged into results.

**Comment by hjoliver** [comment]
Yes, I've flagged .bashrc etc. to the user. Unfortunately I don't have access to his home dir to check that.

**Comment by hjoliver** [comment]
... yep, user says "there was a rogue `svn ---version` in [his login scripts]".
