### ISSUE TITLE
Graph hides the drawer when in responsive (mobile) mode

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#183]
Found this one while reviewing #182 .

When you have the `Graph` on the UI, and then activates the drawer (left sidebar), its z-index appear to be higher than the drawer, and hides it completely.

![image](https://user-images.githubusercontent.com/304786/62909637-7b8a8180-bdd1-11e9-85d4-533fea42eae6.png)

**Comment by MartinRyan** [comment]
this has been corrected
