### ISSUE TITLE
cylc graph - hook up graph view to real workflow data

### ISSUE THREAD

**Issue by MartinRyan** [cylc/cylc-ui#186]

**Comment by kinow** [comment]
@MartinRyan in case this helps, `NODE_ENV=offline npm run serve` will start the development server, and if you look at `views/Tree.vue`, you should have an example of a screen that is using real workflow data (that has been mocked/copied locally) 👍

**Comment by kinow** [comment]
(that's the screen will display the workflow data when going to Workflows / pick one workflow from the table)

**Comment by MartinRyan** [comment]
draft pull request https://github.com/cylc/cylc-ui/pull/241

**Comment by MartinRyan** [comment]
#289 also runs live data
