### ISSUE TITLE
Create Workflow (icon?) component

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#190]
Not sure if the name is a good one - I'm horrible with names. But see comments in https://github.com/cylc/cylc-ui/issues/145#issuecomment-521568337.

The left sidebar (`GScan`) displays several workflows, and next to their names, the tree displays an icon with play/pause/stop signs inside.

![image](https://user-images.githubusercontent.com/304786/63141179-e4276780-c038-11e9-915a-1cab0bf6496c.png)

**Comment by kinow** [comment]
See comment from @oliver-sanders in the linked PR above:

>
>Should be really easy to implement, the field workflow.status field is either running or held:
>
>```
>query {
>  workflows{
>    status
>  }
>}
>```

**Comment by kinow** [comment]
In the https://github.com/cylc/cylc-ui/pull/301/ PR for GScan component, I'm using Material Design icons. If others approve the design, and using icons instead of SVGs, then this issue won't be necessary.

**Comment by kinow** [comment]
Sorry the enigmatic comment in the other issue. I normally add post-its for this on my desk, but I think I was going somewhere so left a kind of note-to-self in the wrong place. It was related to this comment: https://github.com/cylc/cylc-ui/pull/301#discussion_r344517598

**Comment by oliver-sanders** [comment]
> I'm using Material Design icons

I guess if we wrap this up in a component anyway it makes it easer to change / theme later.

**Comment by kinow** [comment]
Aah. Good point. Had completely forgotten about themes. Might be easier with an svg perhaps.
