### ISSUE TITLE
Remove borders in-between divs like sidebar, toolbar, and main panel

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#193]
See comment from https://github.com/cylc/cylc-ui/issues/145#issuecomment-522875938

We have a thin border (3px I believe, gray-300 color from Material UI) between certain elements, following the initial sketch from #87 .

This issue is for discussion on removing these borders, and having a more flat layout. That would give us a bit more of space, and make the layout "thinner". But there are probably counterarguments for keep using the borders.

Cheers
Bruno

**Comment by oliver-sanders** [comment]
Sounds fine, the borders can definitely be thinner and subtler. We should keep a thin border between similar colours to maintain clear visual contrast. Actually looking around this webpage there are some good examples using thin borders to separate the light grey headers from white boxes.

**Comment by kinow** [comment]
>Actually looking around this webpage there are some good examples using thin borders to separate the light grey headers from white boxes.

Oh! Good example! :smile:

**Comment by hjoliver** [comment]
I think that's the go-ahead then, 3 of us agree, no one disagreed. :+1:

**Comment by hjoliver** [comment]
>  But there are probably counterarguments for keep using the borders.

The arguments against flat design claim that thick or dark borders and fake-3D buttons etc. make a UI easier to understand and use.  However IMO that's probably only at first use, and it discounts the value of aesthetics - an ugly UI annoys me every minute that I use it, regardless of how functional it is.  `gitk` comes to mind.  It's so ugly that I keep looking for something new even though it actually does everything I need.

So ... I think flat design just looks better, and I don't think border lines are necessary at all unless perhaps for clickable elements with low colour contrast.

Note on GitHub's pages, the lines themselves are quite low-contrast, as well as thin.

**Comment by kinow** [comment]
Ok, let's do it :tada:
