### ISSUE TITLE
Gantt view time axis: time zone should be scheduler UTC mode

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#1957]
See discussion on #1946

Requires exposing UTC mode via the schema.

Not super high priority as most (but not all) of our users go UTC-everything.

**Comment by MetRonnie** [comment]
Can we close this and consolidate with #1957?

**Comment by hjoliver** [comment]
This is 1957!  Also, it is a bug IMO.  If you've asked to see event times etc. in local time, and you don't live in the UK, you don't want to see UTC times - it's a non-trivial translation to do on the fly in your head.

**Comment by MetRonnie** [comment]
#1917 sorry
