### ISSUE TITLE
Set in task context menu behaves different than most(?) other options

### ISSUE THREAD

**Issue by jarich** [cylc/cylc-ui#1962]
### Description

If I want to hold, broadcast, edit runtime, view logs etc, I can click on anywhere in the relevant line in the task context menu and get the desired behaviour, although clicking the pencil on the right hand side might give me more options.

This is not true for "Set". If I click anywhere on the Set line, that isn't the pencil, the task context menu closes with no evident effect.

### Expected Behaviour

I expect clicking on the "Set" line to behave the same as Broadcast and Edit Runtime and bring up the Set submenu allowing me to actually set the values required.

**Comment by oliver-sanders** [comment]
Hi,

The `cylc set` functionality seems to be working as expected for me (test using the latest released versions):

![set](https://github.com/user-attachments/assets/686b286a-6038-491d-aa12-ce0959d7c856)

By default, `cylc set` will satisfy all of a task's "required" outputs. Typically this is just "succeeded".

What are the required outputs for the task you are attempting to set?

Note, the `cylc show` command will reveal a task's output completion expression.

**Comment by jarich** [comment]
Thank you for the clarification. Success is optional on the thing I was testing, so that would be the reason for what I was seeing. That's an excellent demonstration, gif. I'll update my documentation.

**Comment by oliver-sanders** [comment]
It's a good point about visual feedback for tasks where success is optional. It's not at all obvious what has happened in this case.

The long-term goal is to be able to track commands after they have been issued so we can display some information about their outcome. E.G, "this task does not have any required outputs". The prerequsite for this is https://github.com/cylc/cylc-flow/issues/3329

There's a vague outline of what this might look like:
* For the CLI: https://github.com/cylc/cylc-flow/issues/4778 and here: 
* For the GUI (see the API On The Fly section) https://github.com/cylc/cylc-ui/issues/87
