### ISSUE TITLE
task status icon and naming

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#201]
Supercedes #194 

**[UPDATE]: AMENDED** (groan!) - see below https://github.com/cylc/cylc-ui/issues/201#issuecomment-523696622

We semi-agreed yesterday that the following server-internal task proxy statuses can all be absorbed into a single task status in the UI, because they all come under the category *"prerequisites satisified, and queued for execution"*:
- **queued** (prereqs satisfied, still in an internal named queue)
- **ready** (prereqs satisfied, still in the sub-process pool queue, for job submission)
- **submitted** (job submitted, still in the batch system queue)

Under normal circumstances users do not need to care about the above distinctions, just that their task's prerequisites are now satisfied and the job is "queued for execution".

However:
- they can easily infer "submitted" from the additional presence of a job status icon and batch system job ID
- they can query a queued task to find out if it is in a particular named queue, or in the sub-process pool queue (but they should only need to do this if their named queues are strongly limiting, or if the subprocess pool is too small).

**Additional proposals**
- we call this queued-for-execution UI status icon **queued** (for obvious reasons)
- for descriptive purposes, if needed we can make the following distinction:
  - queued/*submitted* (has a job ID and job status icon)
  - queued/*submitting* (queued for job submission; in the server either internal-queued or process-pool queued).

- we should *change the names of the server-internal "queued" and "ready" statuses*, because "queued" clashes with the combined UI status, and "ready" is a highly ambiguous name. These are internal so we can be verbose:
   - queued --> **internal-queued** or **named-queued**? (the latter is probably clearer because of course the subprocess pool queue is also "internal").
   - ready --> **process-queued**

## UI task status icons and names

![task-status-icons](https://user-images.githubusercontent.com/2362137/63473034-30a2f500-c4c8-11e9-922e-062193fd7a31.png)

## UI task and job status icons and names
![task-job-status-icons](https://user-images.githubusercontent.com/2362137/63473038-34367c00-c4c8-11e9-8eeb-e3d2d61e1552.png)

(Note the two red-label cases here are purely descriptive, no need for different task icons, because the job status icon clearly shows that the task has moved from an internal cylc queue to the external batch queue).

**Comment by hjoliver** [comment]
Additionally:
- **held** is no longer a state - represent with a "pause" badge on the underlying state

- **retry** is no longer a state - represent as **waiting** with a clock badge (and possibly re-implement with clock xtriggers - which show as nodes in the graph - instead of separate special timer code)

- **expired** is a task status - suggested icon:
![image](https://user-images.githubusercontent.com/2362137/63474019-9d6bbe80-c4cb-11e9-9fac-de3707006fa8.png)

- **runahead** remains a server-internal task status but will not be exposed in the UI  - see [here](https://github.com/cylc/cylc-ui/issues/189#issuecomment-523464945) (and in the following comment).

**Comment by hjoliver** [comment]
## Amended Proposal

@matthewrmshin has pointed out (Riot chat stream), and I agree, that the current "ready" state hides quite a lot of action that can't all be described as "queued":
- job script prep and write (in main process)
- task remote (job host) prep, via a command in the subprocess pool, once per job-host/run/restart
- job submission command queued to subprocess pool
- job submission command execution, in the subprocess pool

We agreed it would be more accurate to describe the above as Cylc's internal "job submission pipeline".  

So on reflection, there are two good reasons to amend the above proposal and give different icons for what's described above as "queued/submitting" and "queued/submitted":
1. users can be confronted with failures in any part of the above "job submission pipeline"
2. "submitted" is actually a special status that can be triggered off of, in the graph.

**Comment by hjoliver** [comment]
Final comment before I go insane :face_with_head_bandage: 

The (amended) set of task status icons above **is the minimal possible set** IF we agree that a) the "submitted" state is special, and b) important and time-consuming stuff has to happen between prereq satisfaction and job submission.  Both a) and b) are self-evidently true, so I think we have reached the end of this discussion.  If that turns out to be wrong again, I will get a new job flipping burgers :hamburger:

**Comment by matthewrmshin** [comment]
Agreed.

The *submitted* status is special, as it indicates that the task has successfully submitted a job to an external batch system, and the job can now be polled, killed, etc.

On the *submitting* state... Users will wonder why their tasks are *stuck* in the *submitting* state, so if they want to know, we need to let them find out *where* and *why* their tasks are (even though the tasks may just be taking their time to get through the pipelines).

**Comment by oliver-sanders** [comment]
> we should change the names of the server-internal "queued" and "ready" statuses

I've collated suggestions from @hjoliver and @matthewrmshin and added a couple from myself.

Feel free to edit this to add others:

queued:

* internal-queued
* named-queued
* on-named-queue
* on-suite-queue
* submission-limited
* submit-queued

ready:

* process-queued
* preparing-submission
* processing-submission
* submitting
* preparing

FYI: I'm quite keen on "preparing" for the ready state.

**Comment by hjoliver** [comment]
Sorry all, I forgot about this issue. The lastest/agreed set of states is now:

- abstract task states:
https://cylc.github.io/cylc-admin/proposal-state-names.html#new-abstract-task-states

- task job states:
https://cylc.github.io/cylc-admin/proposal-state-names.html#taskjob-states

This is slightly different than the most recent proposal above.  Now we have:

- `queued` gets absorbed into `waiting` (with the original waiting icon above)
- `ready` gets renamed `preparing` (with the small-dot icon above)
