### ISSUE TITLE
Graph view changes the application font settings

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#208]
Hi @MartinRyan !

Noticed this one today. Here's the app when loaded:

![image](https://user-images.githubusercontent.com/304786/64082575-2ead2180-cd65-11e9-8028-9a88df16e8da.png)

Clicking on other links the menu and other elements keep the same typography. But after clicking on Graph, the application font settings appear to have changed?

![image](https://user-images.githubusercontent.com/304786/64082582-48e6ff80-cd65-11e9-95e4-6e6a31902b98.png)

**Comment by kinow** [comment]
(fonts seem to be antialiazed?)

**Comment by MartinRyan** [comment]
shouldn't be an issue now
