### ISSUE TITLE
WorkflowService doesn't work with nodesEdges, edges, or any other top level entry

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#209]
The current implementation of the `WorkflowService` is tailored for a GraphQL such as 

```
{
  data: {
    workflow: {...},
    nodesEdges: {...},
    tasks: {....}
  }
}
```

The Vuex store has the methods to store the `data.workflow` object. And the service discards any other top level entry such as `nodesEdges`, `tasks`, etc. Picking only `workflow`.

But while reviewing https://github.com/cylc/cylc-flow/pull/3337 & https://github.com/cylc/cylc-uiserver/pull/70, and experimenting with Cylc UI to confirm nothing was broken, I noticed that the `WorkflowService` never populated the Vuex store.

We can work around it with GraphQL aliases, but it only works until another query is registered that overrides it by requesting `workflows {}`.

Maybe the `WorkflowService` would have to be renamed to `GraphQLService`, or simply refactored to store the `data` in the Vuex store, without picking any of its attributes.

**Comment by dwsutherland** [comment]
Both `tasks` and `nodesEdges` can be sub fields of `workflows` ... but this seems kinda restrictive (as each query will be binned into the workflows by force)... I would vote to use `data`
