### ISSUE TITLE
Disable GraphQL query logging

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#213]
Or enable it via debug, or maybe only when the application mode is development. As otherwise the console will get tons of messages after running a workflow for a long period of time.

**Comment by matthewrmshin** [comment]
I guess there is no easy way to clear out old log entries in the console?

**Comment by kinow** [comment]
Maybe [`console.clear()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/clear), but that could remove useful information as well.

**Comment by matthewrmshin** [comment]
Yes, that seems to blast everything away. I guess we want something that only removes entries older than a certain date/time.

In which case, I guess your original suggestion is best - enable logging only at debug level.
