### ISSUE TITLE
Add progress to the Tasks in the Tree Component

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#220]
For Cylc 7 GUI's, the progress is computed here: https://github.com/cylc/cylc-flow/blob/de7d938496e82dbdfb165938145670dd8e801efd/lib/cylc/gui/updater_tree.py#L248-L263

We want to have a similar behaviour in Cylc 8, and will adopt the same approach initially, tweaking it if we have any issues with DOM updates, styles, etc.

Now that the Tree Component is on master (#203), and the query has been updated to include `meanElapsedTime` and `startedTime` (#198), I think we are ready to update the component and display this information.

**Comment by dwsutherland** [comment]
You can also sort the jobs with a query arg:
`sort: {keys: [“submitNo”], reverse: true}`

This way the first item should be the latest.
