### ISSUE TITLE
Decide what to do when a workflow finishes running

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#221]
At the moment, once a workflow finishes running, the UI will simply display a white page.

If you open a URL for a workflow with any name, it also displays a blank page (e.g. http://localhost:8000/users/kinow/#/workflows/duck)

We could display at the top, using the ControlBar component, that it finished running. Or maybe display somewhere in the UI that the workflow was not found (similar to contact file not found error in Cylc).

I think there are plans to display finished workflows, but we may need a temporary solution if that will take a while to implement.

**Comment by hjoliver** [comment]
>I think there are plans to display finished workflows, but we may need a temporary solution if that will take a while to implement.

Yeah I think ultimately we want to display the final state of the workflow before shutdown, but that would require the UI Server retrieving that information from the suite database and/or the suite definition (the DB does not currently store graph edges...)

For the moment I think the UI should just display "<workflow name> is not running".

**Comment by kinow** [comment]
>For the moment I think the UI should just display " is not running".

It would indeed be better than displaying a blank page. The issue is that the backend returns a valid response when there is no workflow, with simply an empty array.

![image](https://user-images.githubusercontent.com/304786/64927686-2a532f00-d862-11e9-89c6-ee8bcc8cd31a.png)

So for this, we would need an issue in `cylc-uiserver` to return something that tells the UI that the workflow is actually not running I think? Or some other state like "no workflow exists with this name", etc?

**Comment by hjoliver** [comment]
Good point. @dwsutherland - is there anything in the schema at the moment that would allow the UI to conclude that the workflow is not running (as opposed to simply a query that returns no data from a running workflow)?  If not, I guess we need to add an "is_running" field or similar.

**Comment by dwsutherland** [comment]
> Good point. @dwsutherland - is there anything in the schema at the moment that would allow the UI to conclude that the workflow is not running (as opposed to simply a query that returns no data from a running workflow)? If not, I guess we need to add an "is_running" field or similar.

Well, the `workflow` data will always be present if it is running, so no data means it's not running, i.e.:
```
query {
  workflows {
    status
  }
}
```
Not really that different than `ping`  (hence why I didn't include it in the GraphQL endpoints)... 

Although I could include a query that doesn't hit the UIS data-store and goes straight to the workflow, maybe we could use `nudgeWorkflow` mutation for that? for example:
```
mutation {
  nudgeWorkflow(workflows: ["*|*"]) {
    result
  }
}
```
Although we need to catch the client error properly (both for queries and mutations), because if the suite as stopped and the UIS hasn't cleaned up the workflow we get:
```
2019-09-18 16:37:14,491 cylc.uiserver.workflows_mgr ERROR    Suite "noz" already stopped
Traceback (most recent call last):
  File "/home/sutherlander/repos/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 50, in workflow_request
    result = await client.async_request(command, args, timeout)
  File "/home/sutherlander/repos/cylc-flow/cylc/flow/network/client.py", line 149, in async_request
    self.timeout_handler()
  File "/home/sutherlander/repos/cylc-flow/cylc/flow/network/client.py", line 310, in _timeout_handler
    raise ClientError('Suite "%s" already stopped' % suite)
cylc.flow.exceptions.ClientError: Suite "noz" already stopped
```

**Comment by kinow** [comment]
>so no data means it's not running

Couldn't it also mean "no workflow registered with this name"? Even though for the UI it would be simpler to simply say "Not running", maybe some users will want to distinguish between these two?

**Comment by dwsutherland** [comment]
> > so no data means it's not running
> 
> Couldn't it also mean "no workflow registered with this name"? Even though for the UI it would be simpler to simply say "Not running", maybe some users will want to distinguish between these two?

Not registered is a more general encompasses "Not running" I suppose

**Comment by matthewrmshin** [comment]
There are really several states to consider:
* Non-existent suite: return a 404 error or the GraphQL equivalent.
* Non-running suite:
  * An installed suite, never run.
  * A suite that has stopped. Can restart.
* Running suite.

**Comment by oliver-sanders** [comment]
This is all part of GScan / suite list functionality at the UI Server which is where we need to go database diving and filling in the bits of information we can't obtain from running suites.

**Comment by oliver-sanders** [comment]
I think we can close this as superseded by #332 (and the display of stopped workflows in GScan)
