### ISSUE TITLE
WorkflowService produces exception if there is no query to execute

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#226]
The current design in `WorkflowService` demands that once initialized, the singleton will keep running queries in the polling way (soon to be changed).

However, if after the singleton has been created, the user navigates to a page without the need for any GraphQL query, what happens is that the `WorkflowService` is still alive and asking the ApolloClient to execute queries.

But without a query ApolloClient throws an error as reported in #224 

Simply adding an `if` or trying to stop the polling could fix it. But I think we may need to actually improve this design a bit. If you create the singleton when looking at `/#/workflows/`, but then decides to spend the rest of the day on a page like `/#/bee` that produces 404, it appears that the `WorkflowService` instance is still around and live, even though it is not necessary.

**Comment by hjoliver** [comment]
I vaguely recall we discussed something like this in Exeter: if user navigates away from a workflow, keep the subscription for say 30 seconds in case they quickly come back, else delete it (and recreate from scratch, as if for first visit, if they come back again later than that).  By extension, if there is no subscription at all (no current workflow views) then shut down (/hold?) the WorkflowService completely after 30 seconds.

**Comment by kinow** [comment]
>I vaguely recall we discussed something like this in Exeter: if user navigates away from a workflow, keep the subscription for say 30 seconds in case they quickly come back, else delete it (and recreate from scratch, as if for first visit, if they come back again later than that). By extension, if there is no subscription at all (no current workflow views) then shut down (/hold?) the WorkflowService completely after 30 seconds.

Oh, alright. That's tricky, we may have to move this requirement to an issue. And fix this issue for 0.2 preventing it from throwing the error/exception.

**Comment by kinow** [comment]
Issue gone! It was probably fixed either in the recent commits that fixed WebSockets, or some other earlier commit.

![image](https://user-images.githubusercontent.com/304786/72784414-a4bb1200-3c8d-11ea-8c1a-46b2eb00cd6a.png)

It's also possible to view the number of subscriptions in the console.

![image](https://user-images.githubusercontent.com/304786/72784501-d633dd80-3c8d-11ea-945a-096d73ca7d19.png)

Then visiting a page that doesn't need any query or subscription

![image](https://user-images.githubusercontent.com/304786/72784535-e8ae1700-3c8d-11ea-9104-4fa46878a68b.png)
