### ISSUE TITLE
Implement Tree leaf node, with extra information

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#228]
From previous discussions, we decided to have a collapsed item (users can expand it if necessary) with extra information.

While no replacement for the table, it will provide extra information that is essential for managing workflows.

**Comment by kinow** [comment]
Will start working on this tomorrow morning :+1:

**Comment by kinow** [comment]
Found a screenshot in [another issue](https://github.com/cylc/cylc-ui/issues/145#issuecomment-520655604). I will aim at having something similar to this - hopefully - by the end of this week or earlier.

![image](https://user-images.githubusercontent.com/304786/62909031-ff8f3a00-bdce-11e9-9da1-878718956ec0.png)

**Comment by hjoliver** [comment]
> While no replacement for the table, it will provide extra information that is essential for managing workflows.

I would say it is a replacement for the table, except for the rare case where users want to sort a table full of data by (e.g.) start time, and thereby quickly compare start times for a bunch of jobs. 

In the meeting we more or less agreed to leave the table view for after alpha-1 release, and *probably* a) not complicate the tree view by trying to make it double as a table view; and b) do a separate non-tree (flat) table view for the above use case.  So we should put up a separate issue for the table view.

**Comment by kinow** [comment]
>So we should put up a separate issue for the table view.

Oh, good point. Let me create it and link with the issue for components.

**Comment by kinow** [comment]
Changed query to include `batchSysName`. I believe we already had everything else needed to reproduce the example above. Now populate an extra child in each task.

Normal entities have the `__type: 'task|cyclepoint|etc'`. So will use `__type: 'leaf'` for this one (no creativity with names). Will also log another issue as I think GraphQL gives you `__typename` or similar field with the entity type. Maybe we could use that instead of duplicating the information in another field.

**Comment by kinow** [comment]
First look at the component (still with scaffolds around it, but soon will be looking much better).

![image](https://user-images.githubusercontent.com/304786/65000120-8db28f00-d93e-11e9-93ba-2f84466adef3.png)

**Comment by kinow** [comment]
After lunch will add the code to hide/display it, and also need to tweak how I calculate the margin-left (it is a child of the job, so I had to force it back to the left, so that it matches the design sketch, but did so with a hard-coded value of --90px; this needs to be calculated based on the depth of the node).

![image](https://user-images.githubusercontent.com/304786/65001656-8c846080-d944-11e9-87e4-588d73c26920.png)

**Comment by kinow** [comment]
Work happening on this branch: https://github.com/cylc/cylc-ui/compare/master...kinow:add-leaf-node

**Comment by kinow** [comment]
Added option to expand/collapse, and made it collapsed by default.

![GIFrecord_2019-09-17_125045](https://user-images.githubusercontent.com/304786/65003301-0cfa8f80-d94c-11e9-8dc3-b9ef3ebc199a.gif)

**Comment by kinow** [comment]
- Adjusted background to match the one in the sketch (ligher, matching the left sidebar, so not exactly what you see in the GIF above now).
- Added code that calculates the margin-left and marging-right dynamically, so when we add families, it should still work with no change required :crossed_fingers: :tada: 
- Adjusted the size for different viewports, and it appears to work fine with mobile

NB: I did not implement the close button. Is it necessary, or could it be discussed? My rationale for that was 1) in the large view port, it would be better if it were closer to the mouse.. on my monitor the right corner is quite far away and it's annoying to have to move the mouse all the way over there to close it, 2) toggling on click seems to be intuitive, and 3) positioning the element correctly wouldn't be really simple.

**Comment by hjoliver** [comment]
@kinow that is looking good :+1:   Can we also have all the other data in the leaves, that you see in the cylc-7 tree/table view?   (I'm off now for a bit BTW, back in an hour...).

**Comment by kinow** [comment]
>that you see in the cylc-7 tree/table view?

Sure @hjoliver , let me just chase an image of the tree/table to add to this ticket and use as reference. Will update the PR in a bit.

**Comment by kinow** [comment]
Will use this screenshot from the Cylc website (note to self, fix your Cylc 7 environment to compare with Cylc UI and help testing 7.8.x releases)

![gcylc-tree](https://user-images.githubusercontent.com/304786/65004102-4da7d800-d94f-11e9-9f77-e5bd35f04d3e.png)

**Comment by hjoliver** [comment]
That's right. 

You can probably omit state (since it's redundant info).

Definitely need "submit time", "finish time", and "mean execution time" as well as "start time".

Might as well add "latest message", although we probably want to improve that in future, e.g. to list all messages not just the latest.

And bear in mind that we may add more info in future - but I presume that's easy so long as any new data is supplied by the back end?

**Comment by hjoliver** [comment]
(Now I'm really gone for an hour!)

**Comment by kinow** [comment]
Done @hjoliver , except for "mean execution time". We have the `meanElapsedTime` on the `Task`. But it is formatted as... a number I think? Not sure how to add this one.

>And bear in mind that we may add more info in future - but I presume that's easy so long as any new data is supplied by the back end?

It should be, but I prefer to document it to fellow developers. Added a section on this [Wiki page](https://github.com/cylc/cylc-ui/wiki/TreeItem-Component) explaining how to do it.

1. Modify the GraphQL query in the view
2. Modify the GraphQL query in the mock data (optional, but useful for developing with static data)
3. Modify the `TreeItem` component adding more fields to the `data: { leafProperties: {} }` property.

It is important to note that the code is iterating `leafProperties` and setting `title` and `property` in the UI.

![image](https://user-images.githubusercontent.com/304786/65005272-687c4b80-d953-11e9-8874-c2d69e7ec84f.png)

So if you want to add something that is not in the `Job` node, you have to move the data there first. But you can easily do that in the function that is re-creating the data structure with hierarchy in the Vuex store (as done in the commit I've just added to the PR and linked in the Wiki).

**Comment by kinow** [comment]
Screen shot of what the PR should look like now.

![image](https://user-images.githubusercontent.com/304786/65005544-4a631b00-d954-11e9-83c8-ec13fb5dfa66.png)

On mobile viewport (Galaxy S9):

![Screen Shot 2019-09-17 at 14 06 55](https://user-images.githubusercontent.com/304786/65005596-77173280-d954-11e9-9e6d-19bfb60ed9df.png)

**Comment by kinow** [comment]
Triagle that stay at the top of the leaf was done with the simple trick from this tutorial: https://css-tricks.com/snippets/css/css-triangle/

**Comment by dwsutherland** [comment]
@kinow nice work!  I guess the job sorting will happen when the progress icon PR goes in?

**Comment by kinow** [comment]
>@kinow nice work! I guess the job sorting will happen when the progress icon PR goes in?

Thanks! Yup, the fix for the `checkpoint.js` and `eslint-disable` too (though I had to include it here too so that the build was pass 😞 so many merge conflicts will happen haha)
