### ISSUE TITLE
Handle time zones when computing the progress bar

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#237]
From https://github.com/cylc/cylc-ui/pull/223#discussion_r325267043

The browser Date object will work on the user TZ.

But the startedTime used in the formula could be in any TZ the user configured the workflow.

**Comment by kinow** [comment]
Setting to 0.2, is that Ok? Or do we need 0.1 handling time zones correctly? We can release 0.2 shortly after if necessary too - [RERO](https://en.m.wikipedia.org/wiki/Release_early,_release_often)

**Comment by kinow** [comment]
Comment from @matthewrmshin :

>The started time string always has a time zone. Does Date.parse recognise and handle that automatically? If so, the subsequent duration calculation should be correct regardless?

**Comment by kinow** [comment]
On `Date.parse`, I think it handles the time zone.

But https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse:

>It is not recommended to use Date.parse as until ES5, parsing of strings was entirely implementation dependent. There are still many differences in how different hosts parse date strings, therefore date strings should be manually parsed (a library can help if many different formats are to be accommodated).

And https://stackoverflow.com/questions/33908299/javascript-parse-a-string-to-date-as-local-time-zone:

>Parsing of date strings using the Date constructor or Date.parse (which are essentially the same thing) is strongly recommended against.
>
>If Date is called as a function and passed an ISO 8601 format date string without a timezone (such as 2015-11-24T19:40:00), you may get one of the following results:

I was trying to use JS' `Date` to avoid adding [moment.js](https://momentjs.com/) as dependency, but I think for this issue, we might consider adding moment.js even if `Date.parse` is working for us.

**Comment by hjoliver** [comment]
I believe we're OK as we're using "seconds since Epoch" as time, which is UTC by definition, both for `startedTime` (computed by Python `time.time()` server-side) and Javascript `Date.now()` in the UI.

**Comment by hjoliver** [comment]
https://en.wikipedia.org/wiki/Unix_time

*It is the number of seconds that have elapsed since the Unix epoch, that is the time 00:00:00 **UTC** on 1 January 1970, minus leap seconds*

**Comment by kinow** [comment]
At least my workflow I runs on UTC (UTC mode = True), my computer is set to New Zealand time, and the progress bar worked fine. I'm still not confident to say it will work 100% on every device (see issues about Date.parse).

Perhaps we can leave this issue open and move to 1.0 @hjoliver ?

**Comment by hjoliver** [comment]
> At least my workflow I runs on UTC (UTC mode = True), my computer is set to New Zealand time, and the progress bar worked fine.

Same.  I think that proves there's no problem and we can close this issue.

> At least my workflow I runs on UTC (UTC mode = True), my computer is set to New Zealand time, and the progress bar worked fine.

Those issues seem to be to do with parsing of date strings.  We're not doing that in the progress function, only calling `Date.now()` and then comparing integer values (seconds-since-epoch). I would think that `Date.now()` gets the system time from the browser, which (hopefully) doesn't involve parsing a date-time string.  

On that basis, I vote to close this (can always reopen later if we find any evidence of a real problem)

**Comment by kinow** [comment]
>On that basis, I vote to close this (can always reopen later if we find any evidence of a real problem)

Works for me 👍
