### ISSUE TITLE
cycle point order not sorted

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#238]
The GraphQL query on master (since yesterday) has:
```javascript
taskProxies(sort: { keys: ["cyclePoint"] })
```
 but the cycle points still aren't ordered correctly in the tree view:

![shot](https://user-images.githubusercontent.com/2362137/65088637-3f6cc100-da0e-11e9-9ff7-76aa09a514c2.png)

**Comment by hjoliver** [comment]
We can bump this to 0.1 if it happens to be an easy fix (?)

**Comment by kinow** [comment]
It should be easy to fix (I'm stuck with the leaf node... I should have done that in vuetify 2.x 😢). I will try to confirm using GraphiQL or maybe ask for help from @dwsutherland to check that the data is coming ordered as requested. If so, there must be something missing in the UI/Vue.js code that needs to be done to display it correctly.

**Comment by dwsutherland** [comment]
Ah yes, use the snake_case version of `cyclePoint`  (`cycle_point`)  ... I could probably implement camel to snake on the back end though...

**Comment by dwsutherland** [comment]
Also I should have set a default for `reverse` ... Heck I'll put a `cylc-flow` PR up...

**Comment by kinow** [comment]
Aaahh. So it doesn't throw an error or warning in this case? That's a bummer, but looks simple to fix - hopefully

**Comment by dwsutherland** [comment]
> Aaahh. So it doesn't throw an error or warning in this case? That's a bummer, but looks simple to fix - hopefully

Yeah, if the key is not a field of the data element.. then it ignores it.
