### ISSUE TITLE
'cylc hub' link doesn't respect base_url

### ISSUE THREAD

**Issue by ScottWales** [cylc/cylc-ui#258]
**Describe the bug**

When cylc 8 is running on jupyter hub with a base_url set, e.g.
```
# jupyterhub_config.py
c.JupyterHub.bind_url = 'http://127.0.0.1:8000/cylc'
```
the dashboard link points to `http://127.0.0.1:8000/hub/home` instead of `http://127.0.0.1:8000/cylc/hub/home`

**Release version(s) and/or repository branch(es) affected?**

8.0a1 installed through conda

**Steps to reproduce the bug**

Add above excerpt to `jupyterhub_config.py`, start the server and check the 'cylc hub' link on the dashboard

**Expected behavior**

Link should point to `http://127.0.0.1:8000/cylc/hub/home`

**Screenshots**

![Screenshot from 2019-09-25 11-38-06](https://user-images.githubusercontent.com/161133/65562247-fe822880-df88-11e9-996e-66e485647a95.png)

**Additional context**

The bind_url is set so I can run cylc behind an apache proxy that also runs other services

Manually going to the hub url works, it's just the link that's broken

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Successfully reproduced the issue :+1:

**Comment by kinow** [comment]
In JupyterHub, this is done by a template file that initializes a global value at attaches it to the `window` object.

https://github.com/jupyterhub/jupyterhub/blob/5b13f96162b77b4ae23306327cd700b8faeb299c/share/jupyterhub/templates/page.html#L62-L64

In our case, our best option - other than replicating JupyterHub's approach - would be to query a service on startup I think.

**Comment by kinow** [comment]
Here's a possible solution. If we add #260, the user information contains:

```json
{
  "kind": "user",
  "name": "kinow",
  "admin": false,
  "groups": [],
  "server": "/cylc/user/kinow/",
  "pending": null,
  "created": "2019-07-16T22:25:30.679281Z",
  "last_activity": "2019-09-25T05:18:47.041040Z",
  "servers": null
}
```

If this information gets stored in Vuex, we can use it to get the `server`, minus `kind` and `name`, to retrieve the Hub base_url. `kind` _could_ vary (need to check docs) for admin users, so perhaps fix that part as `/user/${name}/` and remove that from the `server`.

**Comment by kinow** [comment]
Once #260 this one should be fairly simple to fix. Will send the PR later after the other one is merged :+1:
