### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#264]
Thanks to @sadielbartholomew for raising this issue on Riot.

**Comment by kinow** [comment]
And blame is on me for completely forgetting about it 😬 

The file is one requirement for this issue, the other is the `package.json` entry: https://docs.npmjs.com/files/package.json

Once the license is changed in `package.json`, the package lock file also needs to be changed (i.e. run `npm install`). Otherwise it will cause a change if somebody else runs it in their environment.

**Comment by satblip** [comment]
But which license? MIT?

**Comment by kinow** [comment]
Hi @satblip 

>But which license? MIT?

Everything else in Cylc (cylc-flow, cylc-uiserver, etc) is licensed under GPLv3. I believe that's what we will use here, but just to confirm, ping @hjoliver

**Comment by matthewrmshin** [comment]
Also need a CLA like the one in cylc-flow:
https://github.com/cylc/cylc-flow/blob/master/CONTRIBUTING.md

**Comment by kinow** [comment]
Thanks @matthewrmshin , created https://github.com/cylc/cylc-ui/issues/265 to track the CLA file.

**Comment by hjoliver** [comment]
@kinow - I see no reason to use a different license than for the rest of the project. So yes GPLv3.

**Comment by kinow** [comment]
Thanks for confirming @hjoliver .

@satblip feel free to submit a PR with the update. It needs to have 

- the license file
- update the package.json
- run npm install to update the lock file (preferably this should change just the license in the lock, no dependencies)

In case you are interested in doing this for Hacktoberfest, no hurry from us, feel free to submit it after October 1st :+1:

**Comment by kinow** [comment]
After speaking with other project maintainers, looks like we will need LICENSE and CONTRIBUTING.md before the Hacktoberfest, so contributors can accept the CLA.

I have a few more simple issues that we have been postponing, so I will create them here and label with hacktoberfest.

Thanks
Bruno
