### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#265]
From https://github.com/cylc/cylc-ui/issues/264#issuecomment-535206124

We will need a CONTRIBUTING.md file similar to the one from cylc-flow.

**Comment by itssadon** [comment]
Hi! Can I work on this (as an aside, I will probably wait to put up a PR until Hacktoberfest officially starts on 10/1)?

**Comment by kinow** [comment]
Hi @itssadon,

Sure thing. We are assigning the labels for now, but I believe most action will start next week 🙂 but feel free to ask if you have any question in the meantime too.

Thanks
Bruno

**Comment by kinow** [comment]
Hi again @itssadon !

Actually, after speaking with other project maintainers, looks like we will need LICENSE and CONTRIBUTING.md before the Hacktoberfest, so contributors can accept the CLA.

Sorry, but stay tuned because I have a few more simple issues that we have been postponing, so I will create them here and label with hacktoberfest.

Thanks
Bruno
