### ISSUE TITLE
Use const or let instead of var

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#271]
We have a couple of files that need some quick updates, replacing `var` by `const` or `let`.

- `gquery.js`
- `vue.config.js`

These should be quite easy to locate, or WebStorm can be used to quickly locate which ones need fixing, or VSCode or another IDE or a linter.

EDIT: just to note that one review should do. Minor change, the unit tests will cover some of what will be changed, but a quick manual test with env=offline won't hurt :+1:

**Comment by kreatemore** [comment]
Thanks @kinow I was utterly lost for a couple of minutes there 😅  - but browsing at the other repo I saw some issues where I might be able to contribute 🤞

**Comment by kinow** [comment]
That's great @kreatemore ! I just finished looking for easy issues for the hacktoberfest on this repository. Will take a quick look at cylc-uiserver now, but will probably finish tomorrow morning (NZ time for me). :+1: Feel free to comment on any issue you'd like to know more about or to give it a try and submit a PR.
