### ISSUE TITLE
Remove unused theme components

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#272]
We have now upgraded to Vuetify 2.x. In the process, we copied old files as well as new files. Among these files, there are some components used by the creative-tom's theme, but that are not used in our project.

So we can safely remove them, and add if necessary. They are:

- `src/material/Card.vue`
- `src/material/Notification.vue`
- `src/material/StatsCard.vue`

While these components are nice, relying on them would mean having to keep an eye on updates on both Vuetify and creative-tom's theme. So far we've been able to use just Vuetify, so I believe it would be safer to remove these for now :+1:

**Comment by garrlker** [comment]
I'm gonna knock this out if no one else has gotten to it yet.

**Comment by kinow** [comment]
Fixed in #279! Thanks again @garrlker !
