### ISSUE TITLE
Update to Vuetify 2.1

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#276]
Vuetify announced the 2.1 release. We recently moved from 1.5 to 2.0. This next update should be much simpler. Change log: https://github.com/vuetifyjs/vuetify/releases/v2.1.0

**Comment by MikeLenoir** [comment]
New to all of this so please bear with me, does this just need to be updated in the package.json file under dependencies or is it much more involved than that?

**Comment by kinow** [comment]
Hi @MikeLenoir 

No problem, feel free to ask as many questions as you'd like. We've all been new to certain aspects at some point :)

>does this just need to be updated in the package.json file under dependencies or is it much more involved than that?

Not sure. I had a quick look at the changelog, and it seems to be adding new things that are not used in this project. So in theory updating package.json, running npm install, should either start up the application correctly, or display errors in the console or in the browser console.

I always use an IDE to inspect the code after an update like this, as it is normally able to catch errors in attributes, component names, etc.

Thanks!
Bruno

**Comment by MikeLenoir** [comment]
Thanks for the info and offer to answer any questions. Everything builds properly when making the change to the package.json and there are no errors in the console. When I looked at the docs it says, "There are no upgrade steps to go from v2.0 to v2.1" so not sure if this means there are no breaking changes by upgrading from 2.0 to 2.1.

**Comment by kinow** [comment]
I think it means it should be an update that is backward compatible :tada: Only bad news is that looks like someone beat you to it, and prepared a PR before. But that PR needs to be fixed to address just one issue instead of two. Let's wait a bit for @kylerits to reply on my feedback there :+1:

**Comment by MikeLenoir** [comment]
Thanks for the heads up. I pushed the changes again after running npm install and see the lock file is updated. When I push the changes a second time does that update the pull request or is there something else I need to do? Let me know if I need to delete my PR so it doesn't conflict with the other one. Thanks.

**Comment by kinow** [comment]
> Thanks for the heads up. I pushed the changes again after running npm install and see the lock file is updated. When I push the changes a second time does that update the pull request or is there something else I need to do? Let me know if I need to delete my PR so it doesn't conflict with the other one. Thanks.

No problems. And it updates the pull request for you. You can also open your PR and take a look at the "Commits" tab. There are two now: https://github.com/cylc/cylc-ui/pull/278/commits

Some projects try to enforce that each contribution has a single commit (we don't :slightly_smiling_face: ). This involves some Git-fu, as you would need to rebase/squash your commits.

Let's leave your PR open for now until the other one is updated and merged. But if you would like to try rebasing/squashing your commits in the meantime, it's a good practice and may be helpful for later :+1: 

Or if you know how to write Mocha tests, feel free to send another PR with some unit test for a part of the [code that is not tested yet](https://codecov.io/gh/cylc/cylc-ui/tree/master/src).

**Comment by kinow** [comment]
@MikeLenoir hmmm, I may have to tackle this one myself. I did a quick manual testing using your branch, and realized there are few differences after updating to 2.1.0.

Before:

![image](https://user-images.githubusercontent.com/304786/66179706-832a2080-e6c6-11e9-9d1b-de78f1b79eb8.png)

And after:

![image](https://user-images.githubusercontent.com/304786/66180249-c5546180-e6c8-11e9-899f-461709463e5a.png)

Looks like the Drawer styles have changed. And the drawer is not working when viewport is resized to medium/small:

![image](https://user-images.githubusercontent.com/304786/66180275-dc934f00-e6c8-11e9-80ec-b223c8ca1ac4.png)

So these fixes would have to be part of the fix for the issue too :disappointed_relieved:

**Comment by MikeLenoir** [comment]
I accidentally closed the PR! I just repushed the vuetify changes.

**Comment by MikeLenoir** [comment]
@kinow I can take a look at this if possible. If you think it is something you personally need to handle then I understand. However, I will be keeping an eye on the Repo moving forward and helping out when possible as appreciation for how kind you were to a newbie like me : )

**Comment by kinow** [comment]
> @kinow I can take a look at this if possible. If you think it is something you personally need to handle then I understand. However, I will be keeping an eye on the Repo moving forward and helping out when possible as appreciation for how kind you were to a newbie like me : )

@MikeLenoir it's going to be a boring task of having to go through the pages, slowly compare how each element looks like for mobile and for desktop. There are other tasks that I think are simpler and more fun if you are getting started.

And I am newbie too in many subjects, so I also appreciate your effort in trying to understand how cylc-ui works, and where you could contribute :-) 

Feel free to create issues or pull requests if you find anything not working well, or if you have an enhancement.

Cheers
Bruno
