### ISSUE TITLE
Query ownership

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#304]
**Describe exactly what you would like to see in an upcoming release**

At the moment, it is hard to tell which GraphQL query is being executed. Looking at the #301 PR, the `App.vue` has a query (which may change as that PR is still under review, and maybe `GScan.vue` is a better place to move that query to).

However, you cannot inspect the objects with Vue Dev Tools browser extension. The component in `App` uses a `const QUERIES` declared outside of the component.

The query is then used in a singleton `workflowService` imported from a module, also not viewable in the browser extension. The queries are logged in the console, but the object structure is complicated.

The only way to really tell which query is being executed is through the Network tab, but that makes it harder to troubleshoot when you are not sure whether the query has been changed or not.

**Additional context**

**Pull requests welcome!**

**Comment by kinow** [comment]
We have an `$apolloData` also added by a dependency (`vue-apollo` maybe?), but its `queries` attribute is empty. Maybe we could just change `workflowService` to populate that field.

![image](https://user-images.githubusercontent.com/304786/68451539-0c97ba00-0254-11ea-8a44-0152ff481af4.png)

**Comment by oliver-sanders** [comment]
The information we need is in the `workflowService` which can tell you where each query came from and what the merged result is. I guess it's just finding a way to get that information out.

Perhaps a view?

**Comment by oliver-sanders** [comment]
Coming back to this I quite like the idea of having some developer views:

* One showing the active queries and the merged resultant query?
* One for graphiql?

**Comment by kinow** [comment]
That would eliminate the need for the `console.debug` statements we have now. Bonus points if we can make it some way that users would be able to use and share their queries when reporting problems.

**Comment by oliver-sanders** [comment]
> share their queries when reporting problems.

Oooh.

**Comment by oliver-sanders** [comment]
Punted to new issues.

**Comment by hjoliver** [comment]
> Punted to new issues, is #351 enough to superseded this issue?

Seems to me it is; but @kinow will know better :grin:

**Comment by kinow** [comment]
Way easier to work on these smaller issues now. Thanks @oliver-sanders ! Closing.
