### ISSUE TITLE
Menu disappears when in responsive/mobile mode

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#323]
**Describe the bug**

Menu disappears when the app viewport is resized to mobile/responsive screen size.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Resize viewport to less than 900px - more or less the mobile breaking point for our app, which should hide the drawer and bring the mobile/hamburger menu.

**Expected behavior**

From what I remember, we used to have a hamburger menu (that icon of the three patties stacked together).

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/69920620-ebdb2100-14ee-11ea-844b-36440d15e87c.png)

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Assigning myself, because I am working on the `Toolbar` tests, and can move on to this issue next. And also because 99% chance I was the one who broke it :grimacing:

**Comment by hjoliver** [comment]
I noticed this too, recently, but forgot to report it.

**Comment by kinow** [comment]
Hmm, that confirms it's been broken for a while. I can't remember using Cylc UI in responsive mode in a while. Will actually add a post-it to see how hard it would be to have a functional test for that. It's simpler than most other functional tests we need (like the ones that will involve tree/graph views) and would prevent further regressions.

**Comment by kinow** [comment]
Oh, found out what's wrong.

The `Drawer` component, our left menu, doesn't have the burger menu (displayed when in responsive mode).

The `Toolbar` components has. But I've moved the `Toolbar` to the `Tree` view, as a `Toolbar` is supposed to appear only when looking at a workflow. Before we had it for every page, displaying the page title when not showing a workflow.

A good fix would be to move the burger menu to the drawer or to another component. If not possible, then maybe add the toolbar back to the `App` main component, but hide parts of it when not displaying a workflow, and display the burger menu if responsive (harder to do it well, easier to introduce other bugs :disappointed: )

**Comment by kinow** [comment]
Once #307 is in, I will start working on this. I think I know where to fix it, but would conflict with the work there.
