### ISSUE TITLE
Tree: subtle refactor proposal

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#333]
A bit of spit and polish for the Tree view?

![tree-view-refactor](https://user-images.githubusercontent.com/16705946/70875744-e9fb7c80-201b-11ea-84c3-8557da745824.png)

Questions:

* [x] Change icon ordering?
* [x] Collapse multiple jobs for task nodes?
* [ ] ~~Chronological ordering top-bottom?~~
* [ ] Configurable chronological ordering: bottom-top (most recent cycle point at top) vs top-bottom

Progress:

* [x] Change icon ordering? #606 
* [x] Collapse multiple jobs for task nodes?
* [ ] Chronological ordering bottom-top? (most recent cycle point at top)

**Pull requests welcome!**

**Comment by kinow** [comment]
> Change icon ordering?

+1 I like how jobs are aligned in the proposed new version. Also found the multiple job tidier, and probably easier to maintain in case a task gets something like hundreds of jobs (which would probably break our layout? Or at least trigger DOM reflow :disappointed: ).

> Collapse multiple jobs for task nodes?

+1 If it is really important to know how many jobs failed, and what are the status of these jobs, perhaps we could add a tooltip to the visible job - and display the icon as "decked" jobs, instead of single one, so users are aware it has multiple jobs.

>Chronological ordering top-bottom?
>Chronological ordering bottom-top?

I would prefer to see the most recent information first, but not sure if some users wouldn't want the other way round.

**Comment by oliver-sanders** [comment]
> I would prefer to see the most recent information first

I think I'm leaning this way as well, it's familiar to many due to the rose bush / cylc review interface.

**Comment by hjoliver** [comment]
OK, so we've agreed on chronological order bottom-top (i.e. most recent cycle point at top). I'll update the description...

**Comment by hjoliver** [comment]
"Change icon ordering" and "multiple job collapsing" kind of go together.  job-icon-before-name requires collapsing jobs, or else names can get pushed off to the right.  The new order looks nice and clean, with good alignment. *But* I think it can be good to see if a job had multiple tries without having to expand the tree item.

Can we have our cake and eat it too?  (i.e. allows users to choose or toggle between new-order-collapsed-jobs, and old-order-expanded-jobs)

**Comment by oliver-sanders** [comment]
> But I think it can be good to see if a task had multiple tries without having to expand the tree item.

Take a look at the bottom of the "multiple job collapsing" column, there is a different job icon which is the most recent job overlaying a grey box to show that there were previous job(s).

The reason the background job icon is grey is so we only require the status of the most recent job for the icon which is easier from the data front. But potentially the background job icon could be coloured the same way as the previous job.

**Comment by hjoliver** [comment]
A-ha, sorry, I hadn't viewed the image full-size.  In that case I'm fully on board with the new way.  The stacked icon is similar to what I had suggested for the dot view - we could use the same component for that.

**Comment by oliver-sanders** [comment]
Okay, it sounds like we are all on-board with "Change icon ordering" and "Collapse multiple jobs for task nodes", shall we tick those boxes?

**Comment by kinow** [comment]
@oliver-sanders what about tasks order? Should we have them in chronological order too (not sure if we are able to figure out which task comes first? Or if using task-completion, we could have a task finishing before/after due to failures/retries I think?).

Or should the tasks be in alphabetical order?

**Comment by oliver-sanders** [comment]
> Or should the tasks be in alphabetical order? Or in another order?

I think we should default to alphabetical (which is conveniently the easiest to implement) but also consider implementing other sorting in future work:

* Most recently updated order (like `cylc review`) if there is interest.
* In theory we could sort by any cycle/family/task data (last update time is just one field on the task).
* Namespace definition order (order in which tasks appear in the `suite.rc` file) if there is demand.

Any other ideas for sort order?

**Comment by oliver-sanders** [comment]
Would be good to get the cycle point order fixed before the beta, now that we only display the most recent job the the multiple job collapsing is a nice-to-have we can live without.

**Comment by hjoliver** [comment]
Recent discussions: we probably need cycle point ordering (top down vs bottom up) to be configurable.

**Comment by kinow** [comment]
Marked "Collapse multiple jobs for task nodes?" as done as I think it was implemented some while ago.

**Comment by kinow** [comment]
Created #657 to match the multiple jobs icon in the sketch. Now I think the only thing missing is the configurable sorting of cycle points.
