### ISSUE TITLE
GScan: search and filter

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#337]
Add search and filter functionality to GScan (#139).

![gscan-filter](https://user-images.githubusercontent.com/16705946/70873328-36da5580-2012-11ea-86ec-10559a0ff791.png)

* Search:
  * By partial registration name e.g. "foo' matches "fool/bar" and "bar/fool".
  * Accept globs / regex?
* Filter:
  * Filter by "discrete" data only.
  * May involve adding to the GScan subscription to acquire the required data.

A further enhancement would be searching non-discrete metadata via a different interface. E.G. searching by suite title, description or the Cylc7 "group".

**Pull requests welcome!**

**Comment by kinow** [comment]
Hm, doesn't look too hard to implement. We have filters already in Tree view, will try to add that to GScan too.
