### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#348]
What shall we do with the Footer component?

At present it reduces the space available for the workflow component.

This information isn't that important to most users so we could hide it away a bit.

Options:

* [x] Make it a sticky-footer in the GScan window. *(from comments elsewhere this looks like the most popular option)*
* [ ] Move it to an information button or about menu.
* [ ] Move it into the dashboard.
* [ ] Something else?

**Pull requests welcome!**

**Comment by kinow** [comment]
>At present it reduces the space available for the workflow component.
>
>This information isn't that important to most users so we could hide it away a bit.

No counter arguments for that. I believe you are right.

Happy with any of the options above. Users could click somewhere, or visit another page to tell the version. Though I like being able to quickly see the version in a screenshot.

The footer is not always visible depending on what elements you have in the UI. So users could end up sending screenshots where it would not appear.

What about the first option? " Make it a sticky-footer in the GScan window.". Maybe something like:

![image](https://user-images.githubusercontent.com/304786/71386930-0e77da00-2656-11ea-8023-a09fde869e04.png)

This is the Vuetify documentation site. The left part is the same `Drawer` component we have. At the bottom there is a footer which is the same I think you suggested? I'm +1 for this option.

**Comment by oliver-sanders** [comment]
A sticky footer in the GScan panel with the version number and perhaps a button to get more information.

**Comment by oliver-sanders** [comment]
Superseded by #369
