### ISSUE TITLE
Create a report problem component

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#349]
**Describe exactly what you would like to see in an upcoming release**

We could ad somewhere in the page a component to let users report problems.

It could - maybe - open a github new issue page with pre-populated template like current view and components, gtaphql queries, ui version, maybe even backend if we have telemetry later.

**Additional context**

**Pull requests welcome!**

**Comment by hjoliver** [comment]
A good idea in principle, although we might want to think about the potential for hundreds of GitHub Issues arising, most of which might well be duplicates (requires time to triage...).

**Comment by kinow** [comment]
Oh, good point, hadn't thought about this possibility. That would probably trouble more than help.

**Comment by hjoliver** [comment]
I wonder how other systems handle this?  We could have it send a bug report to a Cylc Discourse topic, but even that might result in hundreds of messages of which very few are real bugs or problems and many are duplicates ("user error" etc.).  The trouble is it takes the onus of users to search the docs for a solution or to look for existing bug reports to add to.  Which sounds good in principle, but only if we have enough people with enough time to deal with the resulting reports...

**Comment by kinow** [comment]
I think this can be closed as superseded by #465 . We can just capture the error, and display a useful message, like "Failed to execute GraphQL query, see browser console for complete error", or display the error.

With this information users can choose how to report the problem.

**Comment by hjoliver** [comment]
Agreed. Longer term a special UI component might be useful, but we have loads of higher priorities at this point.
