### ISSUE TITLE
Migrate to Yarn?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#364]
**Describe exactly what you would like to see in an upcoming release**

Running `npm install` can lead to issues in the lock file, but that can be fixed by using `npm ci` instead. `yarn`, however, doesn't appear to have the same problem - at least the other projects where I have used `yarn` never had issues.

I also have the impression that `yarn` commands are faster.

It is also easier to have multiple source/packages in the same repo/monorepo. Which can be done with `npm` using external tools like [Lerna](https://github.com/lerna/lerna). With Yarn one can use [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).

Today I was upgrading dependencies and one test involved pinning one dependency at the project level. This dependency existed in the dependency chain, but it was a transitive dependency (dependency of another dependency).

It's also easier to pin down dependencies with Yarn using [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/). (the same is possible with pip by specifying the dependency in `setup.py`, or Java Maven, etc). For `npm`, we need an external library too like [`npm-force-resolutions`](https://github.com/rogeriochaves/npm-force-resolutions).

The cons for using Yarn is needing yet another tool in our build software stack, learning curve, and possible issues.

**Additional context**

**Pull requests welcome!**

**Comment by kinow** [comment]
Example of an issue with `npm`: Hilary updated the dependencies yesterday in his PR for tidying up the Graph component #365 . He did not add any new dependencies, but instead removed some Cytoscape dependencies.

That resulted in a new `package-lock.json` generated in his machine. That file was generated during a `npm install` (or maybe `npm ci`?).

This morning I was syncing the `master` branch when `npm ci` failed. `npm ci` does not work when the `node_modules` and `package.json` contents are out of sync. So it asks you to run `npm install`.

Doing so, results in `npm` updating dependencies according to ranges. So unless we pin every dependency (or use [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap.html)), whenever we need to run `npm install`, we will run the risk of `package-lock.json` being updated and appearing in `git status` output.

Maybe `npm shrinkwrap` could work, but it gets some [criticism](https://www.reddit.com/r/javascript/comments/4hqdld/npmshrinkwrap_sucks/) too. This reddit post is from 3 years ago. There is a comment there about the hapi project that used `npmshrink`. But looks like it's now simply [disabling `package-lock.json`](https://github.com/hapijs/hapi/blob/b460a6d86388c880d7344778cc6cdea3a137e666/.npmrc). But I think the risk of doing this would be to have developers with different dependencies locally :sighs:

**Comment by hjoliver** [comment]
> Example of an issue with npm: Hilary updated the dependencies yesterday in his PR ...

Should I have done something different there?  Or is that just an inherent problem with `npm` (hence this issue)?

**Comment by kinow** [comment]
> > Example of an issue with npm: Hilary updated the dependencies yesterday in his PR ...
> 
> Should I have done something different there? Or is that just an inherent problem with `npm` (hence this issue)?

Just a problem with `npm`. It happened before when Martin and I were working on Tree & Graph pull requests.

**Comment by oliver-sanders** [comment]
I'm not familiar with Yarn but I think if we switch the only thing which changes is the `package-lock.json` file becomes `yarn.lock`. I think I've seen projects with both.

Seems more of a developer/sys-admin preference. Sites may prefer to use [pnp](mhttps://pnpm.js.org/en/) for central installations.

Our site will probably use Artifactory which supports [npm](https://www.jfrog.com/confluence/display/RTF/Npm+Registry) and [bower](https://www.jfrog.com/confluence/display/RTF/Bower+Repositories) so the choice doesn't matter.

**Comment by kinow** [comment]
I will prepare a PR this week for this. I used it in the [vue-lumino](https://github.com/kinow/vue-lumino) example project, and in a few private repositories that I have for testing.

So far had no issues, except accidentally running `npm run serve` instead of `yarn run serve` :sweat_smile: But really impressed by how faster `yarn` is (at least in my computer).
