### ISSUE TITLE
Investigate if we can use the GraphQL field nsDefnOrder in the UI

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#384]
**Describe exactly what you would like to see in an upcoming release**

Raised on Riot by @dwsutherland. We are not using `nsDefnOrder`, which gives us the "Order defined in the  workflow def runtime".

```
"nsDefnOrder": [
        "root",
        "FAM",
        "FAM2",
        "FAM3",
        "foo",
        "bar",
        "FAM4",
        "FAM5",
        "FAM6",
        "qux",
        "FAM7",
        "qaz",
        "qar",
        "baa",
        "poll_jin",
        "wog",
        "zan"
    ],
```

**Additional context**

Maybe it could improve/replace how we create the tree hierarchy in the current `Tree` component, that creates the `workflowTree` entry in the Vuex store.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
This will become less important with spawn-on-demand and the n-distance window, because most of the time you will only see a small-ish fraction of all of the defined tasks.

Historically definition order was considered important by BOM people because (I think?) SMS showed tasks in the order they were defined, rather than alphanumerically ordered.  But then SMS also shows all possible tasks in a cycle (easy when you can only run one cycle at at time!).

**Comment by hjoliver** [comment]
I don't think this impacts efficiency in any way - we can remove that label (unless I'm misisng something?).

**Comment by hjoliver** [comment]
The old UI allows users to choose between alphanumeric and definition order, in the tree view.

**Comment by kinow** [comment]
> 
> 
> I don't think this impacts efficiency in any way - we can remove that label (unless I'm misisng something?).

Done. I had thought it was the order it should be displayed in the UI hierarchy. And that we would be able to remove the code I wrote to compute that hierarchy.

**Comment by kinow** [comment]
Closing this one.

Had a look at the returned data,

![image](https://user-images.githubusercontent.com/304786/104966790-a822de00-5a46-11eb-83e6-208b26d9fc99.png)

and while it returns useful information for the order of definitions, we actually need the hierarchy of these tasks too, and for each cycle point. Might be more useful for command line utilities, or internal code.
