### ISSUE TITLE
treeview leaf (job data) layout tweak

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#387]
Response to tab width isn't ideal.
- "latest message" breaks very early
- all data keys break on space
- final (narrowest) position has text overlap (including on the job icon row above the leaf)

![peek-leaf](https://user-images.githubusercontent.com/2362137/73321503-8c5b8080-42a7-11ea-83d1-522ec59dc7b4.gif)

**Comment by kinow** [comment]
Note: the text near the tree item also seems to be a bit broken.

![image](https://user-images.githubusercontent.com/304786/73322767-33d9b280-42aa-11ea-8065-1623fdcd1d5c.png)

![image](https://user-images.githubusercontent.com/304786/73322798-3d631a80-42aa-11ea-8d0b-69149f857e94.png)

Had a brief look and shouldn't be too hard to fix 👍 

Notes to self:

1. `v-col` is supposed to be under `v-row` - https://github.com/cylc/cylc-ui/blob/fe33c61aa3fbe2699cff0cbac363ac430311a23c/src/components/cylc/TreeItem.vue#L70
2. I think `no-wrap` has no effect here (not in the [docs](https://vuetifyjs.com/en/components/grids) of v-col, firefox inspection doesn't show any difference): https://github.com/cylc/cylc-ui/blob/fe33c61aa3fbe2699cff0cbac363ac430311a23c/src/components/cylc/TreeItem.vue#L72
3. Might be easier to implement that part with flex grid, with no wrap or wrap ellipsis, etc.

**Comment by hjoliver** [comment]
> Note: the text near the tree item also seems to be a bit broken.

Yes, I did flag that in my 3rd bullet point in the description above :grin: :
> final (narrowest) position has text overlap (*including on the job icon row above the leaf*)

**Comment by hjoliver** [comment]
![shot](https://user-images.githubusercontent.com/2362137/73323217-8d8eac80-42ab-11ea-8dc6-26af9ff72c84.png)

(mightl be easier to fix after #333 ?)

**Comment by kinow** [comment]
> ![shot](https://user-images.githubusercontent.com/2362137/73323217-8d8eac80-42ab-11ea-8dc6-26af9ff72c84.png)
> 
> (mightl be easier to fix after #333 ?)

Ah! Yup! Definitely much easier!

**Comment by kinow** [comment]
Finished the work on the infinite tree by now. So will start working on this one next.
