### ISSUE TITLE
sidebar: collapse should always be an option

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#389]
Presently the sidebar can only be collapsed in small windows. We should allow users to collapse the sidebar at all times.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Is there a standard-ish way to do this? e.g. burger icon = "open the collapsed sidebar"; collapsed-burger icon = "collapse the open sidebar"?

**Comment by oliver-sanders** [comment]
Burger seems to get used for this a bit.

Personally I think the slide-in nature of a sidebar is more clearly conveyed using an arrow of some kind as a burger bar typically implies a more in-context list (i.e. a dropdown), principle of least surprise and whatnot. I think I used an expand arrow attached to a "tongue" in the early design sketches.

**Comment by hjoliver** [comment]
>  a burger bar typically implies a more in-context list  

I've been thinking of it as not-inappropriate, due to list-of-suites (gscan) sort of resembling a menu

But we could consider your arrow idea.

**Comment by kinow** [comment]
There is a method in the drawer (the name of the component used for the sidebar) to toggle whether it's displayed or not.

That method is used in the responsive mode.

The pre-made layouts of Vuetify place the burger menu in the toolbar. But our toolbar is only displayed when looking at a view with a running workflow.

![image](https://user-images.githubusercontent.com/304786/87480886-5ad24800-c682-11ea-956c-2d423434f332.png)

We could display the mini version of the toolbar instead, and either expand on hover, or have a button to display it.

![image](https://user-images.githubusercontent.com/304786/87480944-79384380-c682-11ea-96b8-a3eea4c88e8f.png)

The issue with expand on hover is that it may trigger DOM reflow. So if you are using it on a view with lots of elements (e.g. graph, or tree, or lumino views) it could cause a brief lag.

**Comment by MetRonnie** [comment]
Superseded by #1137

**Comment by hjoliver** [comment]
Not sure which PR did it, but we can now drag to resize the side bar to zero, in which case the burger appears and can be used  to restore it.
