### ISSUE TITLE
A link may appear in the GScan menu before the workflow data has been received/created

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#390]
**Describe the bug**

I am testing Cylc UI with the complex workflow, and noticed that if you start the UI with no running workflows, for a moment after you start the complex workflow, you will be able to see an empty link in the GScan menu.

I only noticed it because we have an icon with "?" inside a circle. Passing the mouse over, there was no link to the workflow. Showing that while some part of the UI received some data about a workflow, it hasn't gotten the workflow name at that point.

In a few seconds the link text appears, showing "complex", and the icon is also updated.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Start the UI, then start the complex workflow. Keep an eye on the UI and eventually you will see the empty link just before the correct complex workflow link appears.

**Expected behavior**

No icon until the data necessary is available via props/vuex/etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/73416780-e11bfb80-437a-11ea-8685-38c352e4505b.png)

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
ps: 12.9 MB when no workflow is running 🎉 keeps under 15 MB, and with the complex workflow after the infinite tree it's still under 100MB 🎉

**Comment by hjoliver** [comment]
Ha, yes I have seen that too when loading big workflows.

**Comment by kinow** [comment]
Haven't tested the complex workflow in a long time. So decided to have a go and see if this issue still happens (using `master` on all projects).

But instead of testing the UI, I thought it would be better to test with GraphiQL. Running the subscription

```graphql
subscription {
  workflows {
    id
    name
    status
  }
}
```

and then starting the complex workflow, in a few seconds I get the empty values

![image](https://user-images.githubusercontent.com/304786/77115081-8ce7ea80-6a92-11ea-8fcf-37eaf6a60533.png)

and eventually they are populated and everything works fine. But for a few seconds the response contains only empty strings.

We can fix it in the UI. At the moment the code ignores if the workflows doesn't have any familyProxies, taskProxies, or cyclePoints. We could extend this list and also check for name, id, status.

But before doing that, I think it would be better to confirm whether this is an expected result for the GraphQL query, or if the endpoint should return data only when the workflow has name, status, id, etc?

@dwsutherland WDYT? Is returning empty name/id/status valid for Cylc UI Server? Or is it something that we could be changed in the endpoint to only return when the UI Server has the workflow ID/name/etc populated?

**Comment by hjoliver** [comment]
Good question. I'm sure @dwsutherland can explain the current result.

I guess once the subscription is active it is fine if it takes a short while for a modified subscription to take effect, but the very first time it might be best to have a loading symbol or something (but that could be in response to the empty strings I guess, if there's a good reason why that gets returned initially)...

**Comment by dwsutherland** [comment]
> @dwsutherland WDYT? Is returning empty name/id/status valid for Cylc UI Server? Or is it something that we could be changed in the endpoint to only return when the UI Server has the workflow ID/name/etc populated?

It shouldn't serve it up without those fields, it should return nothing (although with the null stripping backend it would probably just serve workflows {})

**Comment by kinow** [comment]
I will create and link an issue in Cylc UI Server then, thanks @dwsutherland !

**Comment by kinow** [comment]
Closing as the Cylc UIS has been fixed too! :tada:
