### ISSUE TITLE
display message triggers

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#402]
[cylc-con-2020]

Display message triggers and [return code](https://github.com/cylc/cylc-flow/issues/3245#issuecomment-530983560) in the UI.

![return-code](https://user-images.githubusercontent.com/16705946/74292862-03137600-4d9e-11ea-8272-3f86caec7cfd.png)

**Questions:**

* [ ] Happy.
* [ ] Should we display messages against the job which produced them or against the task?

**Pull requests welcome!**

**Comment by hjoliver** [comment]
> Should we display messages against the job which produced them or against the task?

Job (otherwise it's a right mess, isn't it?)

**Comment by oliver-sanders** [comment]
> Job (otherwise it's a right mess, isn't it?)

Agreed.

I put this question up because messages though produced by jobs, actually belong to tasks. If a task retries the outputs of its previous runs don't get reset which is kinda confusing.

I think putting the messages next to the jobs makes it clearer that this is the case.

**Comment by oliver-sanders** [comment]
We should be able to right-click on message outputs to reset them, for this we need a small change to the GraphQL spec, see https://github.com/cylc/cylc-flow/issues/3503.

**Comment by kinow** [comment]
Today's work:

![image](https://user-images.githubusercontent.com/304786/98197846-86a86f00-1f8c-11eb-8072-42f4c16451a5.png)

Will prepare a draft PR just to save what I have. Might have a lot to be done, but it's a start I think.

**Comment by hjoliver** [comment]
@oliver-sanders and @kinow  - the diagram above, and presumably the workshop discussion that preceded it, doesn't address multiple custom output messages. In my experience tasks typically register one custom output, or many (e.g. one for each of a series of output files) but in principle any number is possible.  So we need to figure out how to display multiple messages, using:

- the chip UI element (or a list of chips?)
- tooltip over the chip
- and/or the job details "leaf" in the tree (note the job leaf already has the "latest message" field, which this should replace)
- (some other popup-on-click element, but in that case we might was well use the job leaf?)

Thoughts:
- the chip is a nice way to display outputs by default (it fits nicely with exit code and status icons) so we should use it, but:
- if there's only one message, which is often the case, a tooltip is redundant (no point in a tooltip that displays exactly the same thing as the element being hovered over)
- if more than one, should we display:
   - a truncated list in one chip
   - a truncated list of chips?
   - or a vertical list of message chips? (Is that feasible or desirable, within the tree view?)
- have a tooltip that shows all messages, if the chip(s) is(are) truncated?
- or just open the job leaf if the chip(s) (like the job, on the same line) is clicked on? - and the job leaf will show an ordered list of output messages

**Comment by hjoliver** [comment]
As a first step though (from Element chat) you could just tweak the current PR to attach the message the upstream job that emits it (now that the back end can actually provide that!) and have it appear only after the message is received.

**Comment by oliver-sanders** [comment]
For jobs that produce a large number of custom outputs (e.g. the custom output every X time-steps use case) displaying the messages in a horizontal list will never provide a satisfactory interface anyway.

Would suggest displaying the first N messages then putting an ellipsis. At a later date we could potentially add an outputs view (or something more closely mimicking `cylc show`?) that the ellipsis button could send you to.

Thoughts?

**Comment by hjoliver** [comment]
> Would suggest displaying the most recent N messages then putting an ellipsis

The problem with that is it's very dependent on length of the message.  E.g. the "data availability" messages used at BOM are quite long, I think.

Maybe we need to display a small N of messages, but also truncate each one to some fixed number of characters - which could vary depending on how big N is. And hover or click to see more.

As for the "see more" bit, is there anything wrong with putting all messages in full in the job leaf (where "latest message" is now), at least as an interim measure till we figure out a nicer solution?  That would be easy and effective, and arguably appropriate - the job does generate the messages after all.

**Comment by oliver-sanders** [comment]
Can use CSS to cut-off overflow and insert the ellipsis after.

**Comment by hjoliver** [comment]
The “output name” is merely a label for the trigger in the graph, it is the message that’s meaningful so that’s what needs to be available in the UI one way or another

**Comment by hjoliver** [comment]
E.g. in data availability messages, the message contains all the relevant info. If that wasn’t the case we could just use the label/name and not bother with a message.

At least I’ve not seen many meaningful labels out there, it’s usually a, b, c, out1, out2 etc.

**Comment by hjoliver** [comment]
> el) use case which would totally flummox the UI if we were to display all of them.

You didn’t answer my question about the job details leaf. We could list the messages there (most recent first, potentially truncating after a few lines there too, unless clicked on). That wouldn’t flummox the UI.

**Comment by hjoliver** [comment]
Hmm. What if we *required* labels to be short, listed them in the chips, and associated labels with messages in the job details leaf (or potentially in some popup UI element, but I’m struggling to see a good reason not to use job details here.

**Comment by oliver-sanders** [comment]
* labels in chips, truncated to a few chips, or to some width by CSS
* message in chip tooltips

:+1:

> all (label, message) pairs listed in job details leaf

Sounds good in principle, might need to limit the number of messages shown as there can be hundreds of custom outputs per task.
