### ISSUE TITLE
Dashboard responsiveness problem

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#407]
The Workflows column gets wider (and pushes the Events column across) as the window gets narrower:
![peek](https://user-images.githubusercontent.com/2362137/74788847-c6a0c680-5317-11ea-8b4c-117adc4e597e.gif)

**Comment by kinow** [comment]
Ooohh. Should be simple to fix. On it in a bit (just finishing another PR).

And I'm really happy we have these screencasts/gifs in issues. Much easier to see what's broken.

**Comment by hjoliver** [comment]
> And I'm really happy we have these screencasts/gifs in issues. Much easier to see what's broken.

Yeah it's super-helpful :+1:
