### ISSUE TITLE
More flex-box in the dashboard?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#409]
For very narrow viewports, could the Events box drop down below the Workflows one?

![shot](https://user-images.githubusercontent.com/2362137/74798614-1640bb80-5333-11ea-9052-b9bab3076492.png)

**Comment by kinow** [comment]
I think that's a good idea. Instead of 2 x 6 columns, we can simply use xs12, i.e. 12 column-wide div when viewport is small.

And leave md6 and lg6 (2 x 6 columns when viewport is medium or large).

WDYT?

**Comment by kinow** [comment]
(If you'd like to play with that, there should be some xs6 in views/Dashboard.vue. you can play with those values and see what looks best. Or I will put a PR after I finish my expenses report)

**Comment by hjoliver** [comment]
I'll have a quick look...

**Comment by hjoliver** [comment]
It worked, thanks for the tip!  PR coming...

**Comment by hjoliver** [comment]
(I guess that was very similar to your previous PR - sorry about that, didn't really need a new issue :grimacing: )

**Comment by kinow** [comment]
No worries. That's pretty much what you need yo know about Vuetify's grid system. Now we both know what to change for issues like this one 😁
