### ISSUE TITLE
WorkflowService/GQuery fetches more data than what it needs when GScan + a view/component are used

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#416]
**Describe the bug**

I was looking at the Vuex data store today, and at the JS console in the browser, when I noticed that the query for my tree view was bringing more data than necessary.

When you browse the `/#/dashboard`, we have - at the moment - two queries being merged, one for the `GScan` component, and another for the `Dashboard` view. The resulting query looks like:

```graphql
    subscription {
      workflows {
        id
        name
        status
        owner
        host
        port
        taskProxies(sort: {keys: ["cyclePoint"]}) {
          id
          name
          state
          cyclePoint
          latestMessage
          task {
            meanElapsedTime
            name
          }
          jobs(sort: {keys: ["submit_num"], reverse: true}) {
            id
            batchSysName
            batchSysJobId
            host
            startedTime
            submittedTime
            finishedTime
            state
            submitNum
          }
        }
      }
    }
```

That will bring the same data for all the workflows you may be running. (We need a few more changes in the backend to simplify this query more - see #401.) 

Now when you navigate to the Tree view, you will have two queries, one for the GScan component, and one for the Tree component.

The resulting query looks like:

```graphql
subscription {
      workflows {
        id
        name
        status
        owner
        host
        port
        taskProxies(sort: {keys: ["cyclePoint"]}) {
          id
          name
          state
          cyclePoint
          latestMessage
          task {
            meanElapsedTime
            name
          }
          jobs(sort: {keys: ["submit_num"], reverse: true}) {
            id
            batchSysName
            batchSysJobId
            host
            startedTime
            submittedTime
            finishedTime
            state
            submitNum
          }
          firstParent {
            id
            name
            cyclePoint
            state
          }
        }
        familyProxies(sort: {keys: ["firstParent"]}) {
          id
          name
          state
          cyclePoint
          firstParent {
            id
            name
            cyclePoint
            state
          }
        }
      }
    }
```

So after merging it, the query will bring the complete information for the tree view of all the workflows available.

I **think** it would be better to have the Tree View information (family proxies, cycle points, mode details about jobs, etc) data just for the workflow currently being displayed. And the GScan data (workflow info and preferably no jobs/tasks info after #401) for all the workflows available.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Start 10 workflows, open the tree view of one of these workflows. You will have the tree view information in all the 10 workflows, returned from the GraphQL backend, and put in the Vuex store.

**Expected behavior**

In one bucket in the data store we would have the complete data for the tree view. In another bucket/variable/place we would have the data for the gscan (i.e. no family proxies, cycle points, job details, etc, for the GScan as that component doesn't use that data).

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/75404709-3c3c1080-5970-11ea-9f18-fc9a161ebcfd.png)

See in the screenshot above that while I am viewing the `families2` workflow, we know which workflow we want (the `workflowName` comes from the Vue router via the browser URL) but we end up with data for the `five` workflow tree view too.

**Additional context**

Possibly running 10 workflows like `complex`, then visualizing `five` would make the browser memory/cpu to have high usage for a while.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
> I think it would be better to have the Tree View information (family proxies, cycle points, mode details about jobs, etc) data just for the workflow currently being displayed. And the GScan data (workflow info and preferably no jobs/tasks info after #401) for all the workflows available.

Yes, that's right

**Comment by kinow** [comment]
This was a problem for my current approach for deltas.

I was trying to define which workflow to work on based on the data present. So I would go through the list of workflows and create a tree for the workflow with cycle points, family proxies, and task proxies. But then realized all the workflows had that :/

At the moment, when you navigate to certain views like Workflow or Tree (i.e. /workflows/five or /tree/five, not the components, but the views-components), these views will call a Vuex getter, which is similar to a Vue computed property.

So that getter is computed and gives the data for the UI. This getter-value cannot be altered by components. Which means we cannot modify the tree at the moment, even though we already have the deltas in the UIS.

**Comment by kinow** [comment]
Black to the white board :nerd_face:

**Comment by dwsutherland** [comment]
Yeah, I would think the same (If I read you correctly).

That is; have a subscription (soon to incrementally update) for each view (gscan, tree, graph) for each workflow... (If you need more summary info for #401 let me know, and yes we should use workflow.stateTotals and/or workflow.states only... I may need to create a states by cycle field (that would be easy))

Do you need a "getter" for each view-component?

**Comment by kinow** [comment]
>If you need more summary info for #401 let me know, and yes we should use workflow.stateTotals and/or workflow.states only... I may need to create a states by cycle field (that would be easy)

I think this could be done after the deltas, though not sure if there are no other things that come first priority-wise.

>Do you need a "getter" for each view-component?

In this case it's a single getter, that is called by each view-component that wants to access the hierarchical tree view.

These Vuex getters (and `computed` properties in Vue.js too) are like proxies. The GraphQL response data is stored in the worklfows module, as `workflows.workflows`. Then we have the getter `workflows.workflowTree` that is a function that converts `workflows.workflows` into the hierarchical tree.

That function is evaluated only when the `workflows.workflows` value changes. If that value changes, then the proxy is triggered, causing all the Vue components to react, and this way the UI is updated (that's basically how these two work in Vue, but there are other ways to create reactivity in Vue)
