### ISSUE TITLE
Automate release with GitHub actions

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#475]
**Describe exactly what you would like to see in an upcoming release**

Inspired by work from @MetRonnie and @oliver-sanders on isodatetime. We should be able to use an action to upload the zip to GitHub. Must be even easier than `pip`, as we already have the GitHub token for the action in the env var.

The process is:

- check out with `git`
- `cd $PROJECT_HOME`
- `yarn install`
- `yarn build --optimize`
- `zip -r ../cylc-ui-$VERSION-dist.zip *`
- `sha256sum ../cylc-ui-$VERSION-dist.zip` and save the output somewhere
- Create a tag and a release in GitHub
- Upload the `cylc-ui-...-dist-zip` file to the release
- Add sha256 sum to the file description (for conda Release Managers)

**Additional context**

To avoid issues like in the previous release - https://github.com/conda-forge/cylc-ui-feedstock/pull/4

**Pull requests welcome!**

**Comment by kinow** [comment]
First iteration: https://github.com/kinow/cylc-ui/pull/2

Now going to work the ZIP package creation and upload to GitHub releases (part of our Conda recipe for Cylc UI).

**Comment by MetRonnie** [comment]
Happy to review 👍
