### ISSUE TITLE
Tree component filtering

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#482]
**Describe exactly what you would like to see in an upcoming release**

Allow users to apply filters to the Tree component.

- [ ] Display the filter menu in the UI (see #87 and #337 for reference)
- [ ] Apply filter to the local component
  - [ ] Filter by task name
  - [ ] Filter by task state

**Additional context**

Similar to Cylc 7's GUI feature:

![image](https://user-images.githubusercontent.com/304786/90833539-5c3b1280-e39c-11ea-979e-ad678b5be0bc.png)

**Pull requests welcome!**

**Comment by kinow** [comment]
Note: Cylc 7 GUI filter returned only the branch of the tree with the tasks found.

![image](https://user-images.githubusercontent.com/304786/90838131-20a64580-e3a8-11ea-8a40-6360032b1de6.png)

The example above was a quick test, filtering in the `TreeItem` (recursive component). Telling it to not render tasks that do not match a filter - if provided. And also not rendering the children (jobs) nodes.

While the simplest way to implement it, we end up with child-less nodes in the tree.

Back to the drawing board.

**Comment by oliver-sanders** [comment]
* Filtering per-view.
* The default filters should work in all views.
* Accessible via the [view toolbar](https://github.com/cylc/cylc-ui/issues/471).

I think it would be a good idea to keep the filters simple for now (i.e. job state and possibly task name) and to add other filters slowly when we are able to find efficient ways of implementing them.
