### ISSUE TITLE
Tree component displays task state filters in two lines, breaking the layout

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#513]
**Describe the bug**

Depending on the screen size, you may get two lines in the select element if you have selected many task states.

![image](https://user-images.githubusercontent.com/304786/95028534-4e97dd00-06fd-11eb-926d-eaa48b9d2f96.png)

One alternative could be to show only 4 or 5 items, and show `…` or another indicator that there are more items selected.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

1. Select all the task states in the tree filter
2. Play with your browser width, resizing the window or using FFox mobile preview

**Expected behavior**

Concise layout, without the extra line (which most likely causes reflow, and may result in unexpected layout issues depending on other components/browser engine/etc)

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/95028588-928ae200-06fd-11eb-82e5-76e95721007f.png)

**Additional context**

Related to #512 and #508 

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by elfreelancer** [comment]
Hi!

I would like to help, can you assign it to me please?

**Comment by SoldierCorp** [comment]
Hi!

I would like to help, can you assign it to me please?

**Comment by kinow** [comment]
Hi @SoldierCorp ! Assigned! Do you have some experience with Vuetify or Vue? It doesn't really matter much, but in case you haven't used them, this might be a good starting point: 

- [v-select in our Tree component](https://github.com/cylc/cylc-ui/blob/e0579644abecf5ed4e636da65d9bdb5567474514/src/components/cylc/tree/Tree.vue#L38)
- [v-select Vuetify documentation](https://vuetifyjs.com/en/components/selects/)
- [in case you want to run the complete system (Python + JS)](https://cylc.github.io/cylc-admin/howto/cylc-ui) (update under way on https://github.com/cylc/cylc-admin/pull/113)
- otherwise `yarn run serve` command starts a mocked/fake workflow in the JS app. You should be able to use that for this issue 👍 

And in case you need, just ask :-)

Thanks @SoldierCorp !
Bruno

**Comment by SoldierCorp** [comment]
Thank you @kinow !

I do have experience with Vue and a little bit with Vuetify but still, thank you for share those links :)
