### ISSUE TITLE
gscan for all registered suites (or a subset of them)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#54]
The gscan GUI currently displays running suites, or recently(?) stopped ones.

We could (perhaps optionally) have it display all of a users registered suites, including ones that have never been started or were stopped non-recently, or a given subset of them.  This would make it a good way to see which members of a group of suites that should be running are still running, and to restart them if they're not running (perhaps by a shortcut "restart" right-click menu option in gscan).

**Comment by kinow** [comment]
@hjoliver I just tested this one.

- UI displaying my existing workflows
- I created the folder `five2` with a copy of `five`; the UI did not change
- Issued `cylc register five2` in that directory, command executed successfully; in a couple seconds the UI displayed the `five2` workflow, that was never executed

![image](https://user-images.githubusercontent.com/304786/93943057-d8eb5300-fd85-11ea-986d-810e26ed1e7c.png)

Does it match what you described in this issue?

**Comment by hjoliver** [comment]
Brilliant - yes, we can close this (Jan 2015!) - thanks :bouquet:
