### ISSUE TITLE
Use deltas in GScan

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#542]
**Describe exactly what you would like to see in an upcoming release**

The issue to add hierarchy to GScan #502 would benefit of having deltas in GScan. That way we can more easily update the hierarchy with the deltas.

This should also fix #416

**Additional context**

**Pull requests welcome!**

**Comment by kinow** [comment]
Current GScan subscription query

```graphql
subscription {
  workflows {
    id
    name
    status
    owner
    host
    port
    taskProxies(sort: { keys: ["cyclePoint"] }) {
      id
      name
      state
      cyclePoint
      latestMessage
      task {
        meanElapsedTime
        name
      }
      jobs(sort: { keys: ["submit_num"], reverse:true }) {
        id
        batchSysName
        batchSysJobId
        host
        startedTime
        submittedTime
        finishedTime
        state
        submitNum
      }
    }
  }
}
```

The new subscription query with deltas.

```graphql
subscription OnGScanData {
  deltas (stripNull: true) {
		added {
			workflow {
      	...WorkflowData
      }
    }
    updated {
      workflow {
      	...WorkflowData
      }
    }
  }
}

fragment WorkflowData on Workflow {
  id
  name
  status
  owner
  host
  port
}
```

A workflow first appears as `running` in the `added` section. A few moments (1 second?) later it appears in `updated` too. But I think we should display it as running as soon as we can.

WIP: Still building the rest of the query for the job statuses.

**Comment by hjoliver** [comment]
> the task proxies & jobs are necessary now, I think, until we have fixed #401

@kinow as per comments on Element just now, I'd suggest just don't use a placeholder for gscan tool-tip content until we have the right data from the front end.  It sounds overly difficult to do it by iterating over all the tasks (which gscan should not need) in the meantime.  (Or have I missed something?)

**Comment by kinow** [comment]
No, I was just trying to add the deltas now, for hierarchy. But I think we can wait or leave that out for now. Would it be OK if we had deltas and the hierarchy without the tooltips? And then hopefully add back the tooltips before the beta release?

**Comment by hjoliver** [comment]
(Typo corrected above - I meant DO use a placeholder for gscan tool-tip content)

**Comment by hjoliver** [comment]
> Would it be OK if we had deltas and the hierarchy without the tooltips? And then hopefully add back the tooltips before the beta release?

Yes, that's fine - better than complicating the code to generate the tooltips the wrong way just because the data isn't there yet. :+1:
