### ISSUE TITLE
Workflow view displaying incorrect workflow

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#551]
**Describe the bug**

Found while working on #543 . The workflow displayed in the Workflow view, inside a Lumino widget, may be the wrong one. i.e. not the one you are browsing.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

1. Start Cylc UI with at least 1 running workflow
2. Click on the workflow in GScan
3. Now close the Tree widget component that is added by default in the Workflow view
4. Now click on another offline workflow
5. It should now display the previously running workflow

**Expected behavior**

Display the right workflow.

**Screenshots**

**Additional context**

I did a quick investigation with vue-dev-utils. I think the Workflow view has the right data, and the widget also has the right data. The `variables` field that is passed to the GraphQL query has the right workflow ID. But I **think** the subscription is being reused somewhere.

Probably related to how we manage subscription and Vue views & components lifecycles. Might be related to #454 

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Having a look now …

**Comment by oliver-sanders** [comment]
That is really strange!
