### ISSUE TITLE
filter by task/job state independently in each view

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#56]
See:
- https://github.com/cylc/cylc/pull/1320#issuecomment-83021349
- https://github.com/cylc/cylc/pull/1320#issuecomment-83182130

**Comment by oliver-sanders** [comment]
Filtering by task/job status will be common to most views so there should be some common code to handle this.

Filtering should be independent in each view (e.g. a user might want a view just showing failed tasks and another showing the full suite).

**Comment by MetRonnie** [comment]
I think this is sorted?

**Comment by oliver-sanders** [comment]
> I think this is sorted?

Yes! Views are now filtering independently.

This functionality isn't properly centralised, can boot that to #471
