### ISSUE TITLE
gscan: responsive rows

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#576]
Line wrapping issue in GScan spotted in a screenshot from @hjoliver in https://github.com/cylc/cylc-ui/pull/575.

<img width="246" alt="Screenshot 2021-01-19 at 10 14 44" src="https://user-images.githubusercontent.com/16705946/105020454-38f5bb80-5a3f-11eb-98de-19f86f225b8f.png">

When the GScan column is not wide enough I think the best resolution is to:

* Let the workflow name `overflow: hidden`.
* Move the status icons to the start of the next row.

I.E:

<img width="35%" src="https://user-images.githubusercontent.com/16705946/105021439-71e26000-5a40-11eb-9d81-5748c9666340.png" />

This has the unfortunate effect of cutting off the full name of the workflow, however, it may not be possible to display a long name in a narrow column. We could display the full name in a tooltip and potentially consider smart abbreviations one day.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
I agree with the proposed solution :+1:

**Comment by kinow** [comment]
Taking a look this morning to see how hard it'd be to make it responsive following @oliver-sanders ' solution. (borders are from Firefox dev tools.)

![image](https://user-images.githubusercontent.com/304786/105100309-01a40f00-5b12-11eb-9d9b-7aedad35702b.png)

Getting close to what @oliver-sanders described, I think 😅
