### ISSUE TITLE
Colour coded task names in dot view

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc-ui#58]
It would be helpful to add some indicator of task groups via their visualisation colour in the LED view.

**Comment by kinow** [comment]
Notes from discussion to move to cylc-web:

>  * (Hilary) Agreed. ("LED view" == old name for "dot view", which origially used LED light images for dots) The issue title is a bit misleading - it's really about using `[visualization]` color settings in some way in the control UI - in all views - alongside the live task state colors.

**Comment by oliver-sanders** [comment]
Superseded by #263
