### ISSUE TITLE
gcylc - keep view options client-side

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc-ui#59]
Adjusting some view options in `gcontrol`'s graph view affects other `gcontrol` instances - for example 'Group All Families'. This would be a problem for shared suites, and would probably be best kept on the client side rather than stored remotely.

**Comment by kinow** [comment]
Notes from discussion to move to cylc-web:

>  * (Matt) Browser cookies? Or user session settings on server side? Should probably move to cylc/cylc-web.
>  * (Hilary) Agreed. Not sure how to do it yet, but we don't want one user's family-collapse choices to affect other users viewing the same suite (as happens now)

**Comment by oliver-sanders** [comment]
Superseded by #335
