### ISSUE TITLE
Display non-standard non-output messages

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#595]
... in job leaves. See description of #596

Requires changes to back-end and schema, to supply the data.

**Comment by oliver-sanders** [comment]
> we should display other non-standard messages: e.g. warnings and messages not used for triggering

What kind of messages were you thinking about?

**Comment by hjoliver** [comment]
Tasks can use `cylc message` to send arbitrary "informative" messages to the server, that aren't used for triggering.  Not a high priority.

**Comment by oliver-sanders** [comment]
update: we now appear to have a messages field in the schema and it looks like it works.
