### ISSUE TITLE
cypress/vue

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#610]
[`@cypress/vue`](https://github.com/cypress-io/cypress/blob/master/npm/vue/README.md) looks pretty nice, we should be able to mount individual Vue components for testing.

Would be good for testing. Had a quick go at adding it for testing https://github.com/cylc/cylc-ui/pull/607 but was having issues:

```js
import { mount } from '@cypress/vue'
import Task from '@/components/cylc/Task'

describe('a', () => {
  it('b', () => {
    mount(Task, {
      context: {
        props: { status: 'waiting' }
      }
    })
  })
})
```

<img width="358" alt="Screenshot 2021-03-10 at 12 48 48" src="https://user-images.githubusercontent.com/16705946/110631952-faf35900-819e-11eb-8b3a-ada528be0957.png">

**Pull requests welcome!**

**Comment by wxtim** [comment]
Cyprus e2e testing of #1168  would be a nice case study.

**Comment by oliver-sanders** [comment]
We have now started using Cypress' component testing functionality which does exactly the same thing.

The component tests can be found in `cypress/component` and are run in CI in the `main.yml` workflow.
