### ISSUE TITLE
Mutation errors not reported in the UI for the user

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#613]
**Describe the bug**

I found this one this morning while testing `five`, but I was using Postgres. Re-created environments from master, but reproducing it was a bit hard.

Looks like if I stop the workflow, and then send a hold mutation, I think depending when your mutation arrives at the backend, it may result in an error. That error, however, is only logged to the browser console.

This morning, the error I had was slightly different. I was hold/release-ing my workflow to test it. And at one point it had stopped, but when I sent a hold or release mutation nothing happened. Took me some seconds to realize there could be something in the browser console log.

![image](https://user-images.githubusercontent.com/304786/111092278-7b003100-859a-11eb-8ad6-6488cd725d74.png)

**Release version(s) and/or repository branch(es) affected?**

master

**Steps to reproduce the bug**

1. start a workflow
2. stop the workflow
3. click on the pause icon

There could be more scenarios where errors like this occur.

**Expected behavior**

Either the interface prevents the user from sending mutations depending on the workflow state, and/or it should display a warning so the user is aware that the mutation did not succeed.

**Screenshots**

See description.

**Additional context**

The UIS console contains:

```bash
[I 2021-03-15T14:23:41.689 JupyterHub proxy:319] Checking routes
[I 2021-03-15T14:23:53.384 JupyterHub log:181] 200 GET /hub/api/authorizations/token/[secret] (kinow@127.0.0.1) 18.82ms
2021-03-15 14:24:06,444 cylc.uiserver.workflows_mgr ERROR    five/run1 is not running
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 69, in workflow_request
    result = await client.async_request(command, args, timeout)
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/network/client.py", line 183, in async_request
    self.timeout_handler()
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/network/client.py", line 277, in _timeout_handler
    raise SuiteStopped(suite)
cylc.flow.exceptions.SuiteStopped: five/run1 is not running
2021-03-15 14:24:06,460 cylc.uiserver.data_store_mgr DEBUG    purge_workflow(kinow|five/run1)
2021-03-15 14:24:06,898 cylc.uiserver.data_store_mgr DEBUG    stop_workflow(kinow|five/run1)


```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Closed by #623 to the maximum extent which is currently possible from the information Cylc returns about actioned mutations.
