### ISSUE TITLE
Re-fetch full state if a delta is missed or is bad.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#614]
If delta processing fails, or if the UI somehow misses a delta or any part of it (which we can tell once we switch to integer delta counter instead of checksums), the UI will need to start again from a fresh full-workflow state (otherwise the bad/missed delta will leave the UI in a state that differs from the true workflow state).

(I don't think the UI can ask the UIS to re-send the bad delta ... ping @dwsutherland)

**Comment by oliver-sanders** [comment]
We should also present this to the user in some way so that we are made aware that this is hapening (as it shouldn't happen at all).

**Comment by dwsutherland** [comment]
> (I don't think the UI can ask the UIS to re-send the bad delta ... ping @dwsutherland)

After the deltas are applied to the UIS data-store and sent to the subscribers, they are dropped when the next one comes in.

Probably need to focus on the why, so we can reduce the occurrence and need to refresh the UI store. (?)

**Comment by hjoliver** [comment]
> Probably need to focus on the why, so we can reduce the occurrence and need to refresh the UI store. (?)

Yep.  I don't think we can expect the UIS to keep deltas for possible resend later on.

**Comment by hjoliver** [comment]
We decided in the project meeting just to alert the user and advise to reload the page.  If that's sufficient, then #616 can close this issue.

**Comment by hjoliver** [comment]
Closed by #616
