### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#62]
`npm audit` found a few vulnerabilities again in this project. This issue is a reminder so that I don't forget doing it later (or if anyone feels like trying it, please [feel free](https://docs.npm.red/cli/audit)).

Another reason for creating this ticket is to check with @hjoliver if he received any e-mail from GitHub. I thought it would alert us automatically whenever one of our `npm` dependencies had a CVE?

**Comment by hjoliver** [comment]
>  check with @hjoliver if he received any e-mail from GitHub. 

Nope!

**Comment by kinow** [comment]
Closing this one as GitHub was happy with dependencies (until moments ago when it reported another security issue, which will go to another issue)
