### ISSUE TITLE
aotf: shorter mutation lists

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#621]
The design document shows menus with nice short lists of commands:

<img width="313" alt="Screenshot 2021-03-19 at 15 36 59" src="https://user-images.githubusercontent.com/16705946/111805515-ffb7bb80-88c8-11eb-9772-6ccda5ba9035.png">

However, we have quite a few mutations that could be called in different contexts so the list is quite a lot longer and we still have all of those offline mutations and potentially user-defined ones too #558.

We should try to present a shorter list of more relevant commands with the option to expand to see more. (This was actually a part of the early design sketches and run by a few user groups.)

Ideas to reduce the number of commands:

1) A relevance score based on the number of arguments that relate to Cylc Objects (flows, cycles, tasks, etc) that cannot be satisfied by the context.

    * E.G. If you click on a workflow the trigger mutation would be considered to have a low relevance because it takes tasks as arguments and we are clicking on a workflow not a task.
    * I think this logic would go in `@/utils/aotf:filterMutations`.

2) Pre-defined short-lists.

    * E.G. hard-coded lists of commands to display by default for different Cylc Object types.

Perhaps try (1) and fall-back to (2)?

From the design perspective this would me a "more" button at the end of the list or something like that?

**Comment by hjoliver** [comment]
I think pre-defined would be sufficient.  We know what the most important commands are.
