### ISSUE TITLE
repo name change?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#63]
Just wondering if this repository should be renamed to either:
- `cylc-ui`, to be consistent with `cylc-uiserver`, or
- `cylc-webui`, in case we ever have another UI that is non-webby (ncurses?)

(`cylc-web` sounds a bit odd on reflection...)

**Comment by kinow** [comment]
Will lurk here as normally do in issues regarding choosing names :grimacing: for me these three options all sound OK (`cylc-web`, `cylc-ui`, `cylc-webui`).

**Comment by kinow** [comment]
ping @cylc/core :grimacing:

**Comment by hjoliver** [comment]
I propose **cylc-webui** (to distinguish from the CLI that will remain in cylc-flow, but a bit more explicit  than just "cylc-web") ... but let's see what others think.

**Comment by matthewrmshin** [comment]
My preferential votes are:
1. `cylc-ui`
2. `cylc-webui`
3. `cylc-web`

**Comment by hjoliver** [comment]
OK, `cylc-ui` is nice, for consistency with `cylc-uiserver`. 

Do we need to worry that `UI` typically encompasses CLI too?  (I guess @matthewrmshin thinks not?)

**Comment by hjoliver** [comment]
If agreed that's not a problem, I'm happy to go with `cylc-ui`.

**Comment by sadielbartholomew** [comment]
If it helps make a decision, in honesty I prefer ``cylc-ui`` for its simplicity & consistency. While a CLI is strictly a UI, for me UI dosen't bring to mind the CLI, which I treat conceptually as something separate. Others may not feel the same, but in general I don't believe it will matter.

On that note, it would be nice if GitHub had a vote/poll feature so there is a quick & simple way to register an opinion on decisions such as this. There is a [plug-in app, Polls](https://github.com/apps/polls), which I found from a quick search. Would it perhaps be useful in future, or is it no better than simply using 'reaction' emoji (thumb up/thumb down, as mapped to some option in writing) on comments?

**Comment by matthewrmshin** [comment]
I am satisfied that UI (in this context) will not be confused to encompass the CLI and user configuration files. It should be quite clear that it is the logic for the front-end of the `cylc-uiserver`.

**Comment by hjoliver** [comment]
RESULT: `cylc/cylc-ui`

**Comment by kinow** [comment]
Repo renamed.
