### ISSUE TITLE
Check if the tree view is sorting items in natural order

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#644]
**Describe the bug**

We had an issue some time ago where I think the cycle points, family proxies, task proxies, or jobs, were not sorted in natural order.

So we got `[1, 10, 2]` instead of `[1, 2, 10]`.

This issue is a follow-up so that we verify this behaviour has indeed been fixed. Might be worth to check if this could happen in GScan too.

Apologies for taking so long to create this issue.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Create a workflow that generates cycle points, tasks, jobs, families, with numbers for names that include 1, 2, 10, for instance.

**Expected behavior**

Items sorted as in Cylc 7, in natural order.

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Related, but apparently fixed: https://github.com/cylc/cylc-ui/pull/492#discussion_r489500908

**Comment by hjoliver** [comment]
```ini
[scheduling]
  cycling mode = integer
  initial cycle point = 1
  max active cycle points = 12
  [[graph]]
     P1 = "foo"
[runtime]
  [[foo]]
     script = "sleep 60"
```
![shot](https://user-images.githubusercontent.com/2362137/114967232-2c5ef300-9ec8-11eb-98b2-374b3abca0c2.png)

**Comment by kinow** [comment]
Thank you @hjoliver !!! Will try to fix these next week while the deltas are fixed for GScan.

**Comment by hjoliver** [comment]
Task name sorting (as opposed to cycle points) looks fine:
```ini
[scheduler]
   allow implicit tasks = True
[task parameters]
   m = 1..12
   [[templates]]
      m = %(m)s_foo
[scheduling]
  cycling mode = integer
  initial cycle point = 1
  runahead limit = P1
  [[graph]]
     P1 = "<m>"
[runtime]
  [[root]]
     script = "sleep 60"
```
![shot](https://user-images.githubusercontent.com/2362137/114978650-99c94e80-9edd-11eb-9c77-a0857bebb35d.png)
