### ISSUE TITLE
toolbar/aotf: wrong workflow for mutation

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#678]
Sometimes mutations are run against the wrong workflow.

So far I've only seen this happen with the `play` mutation for a stopped workflow.

Steps to reproduce:

* Create two workflows.
* Select the second in the toolbar.
* Click the mutations button.
* Click the pencil button next to the play mutation.
* Scroll down to the "workflows" field to see what workflow it would run against.

**Pull requests welcome!**

**Comment by kinow** [comment]
@oliver-sanders was it closed by #691 ?

**Comment by oliver-sanders** [comment]
Yep
