### ISSUE TITLE
workflow subscriptions when the hub user != uis user

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#679]
The user from the store is used to construct the workflow ID for the tree view subscription:

https://github.com/cylc/cylc-ui/blob/2042834d65f00ca9a77db1836066c56397221d1d/src/mixins/treeview.js#L39

This is fine so long as the user viewing the UI is the same as the user running the workflow.

However, the user in the store is the authenticated user which may be different. We need to capture and store the workflow owner somewhere so it can be used for this purpose later.

Note that the Jupyter Server plan (https://github.com/cylc/cylc-uiserver/issues/219) means that we cannot get the workflow owner from the URL as that would only work when the UIS is run via the hub and not when it is run standalone.

Ideas:

1. We could add a `User` field to the GraphQL schema.
2. We could add an `owner` field to the userprofile.

I may try (2) as part of https://github.com/cylc/cylc-uiserver/issues/219 as it should be quick.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
@oliver-sanders realized just now that https://github.com/cylc/cylc-ui/pull/724 appears to be related to this issue? Let me know if that PR is unnecessary with this new owner field in the UIS. Or if that approach could still be used (happy to close that PR if it'd be better to use the owner attribute in some way).

**Comment by oliver-sanders** [comment]
Sorry, I'm falling behind with reviewing at the moment, haven't got around to #724 yet.

The tricky thing with the Jupyter Server conversion is dealing with standalone UI servers that use token authentication rather than JupyterHub.
