### ISSUE TITLE
gscan/dashboard show as loading if there are no workflows

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#687]
If a user has no workflows in their cylc-run dir (running or otherwise) then GScan and the Dashboard show their loading state which makes it look like the UI is still connecting to the UIS and hasn't finished loading yet.

Perhaps this should wait until after subscription merging is done? The Dashboard and GScan subscriptions should be mergeable (as they are both multi-workflow "global"-like subscription). When the first delta is received we can say these views have loaded?

**Pull requests welcome!**

**Comment by kinow** [comment]
Duplicate of #671?

**Comment by kinow** [comment]
>The Dashboard and GScan subscriptions should be mergeable (as they are both multi-workflow "global"-like subscription). 

Oh! That's true! I hadn't thought about that one. I'm using GScan + Tree in another branch for testing the merging, but will keep this in mind for testing, thanks!

> When the first delta is received we can say these views have loaded?

See linked issue. IIRC, there's no delta when there are no workflows. Apollo Client and other GraphQL servers use a 1 Query + 1 Subscription approach. The Query provides the initial burst, and the Subscription brings updates.

I think in the other issue we were discussing having the deltas initial burst in other places, but I don't recall the whole discussion.

**Comment by oliver-sanders** [comment]
> Duplicate of #671?

Ah, yes it is, thanks.
