### ISSUE TITLE
toolbar: mutation can be called for the wrong workflow

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#690]
**Describe the bug**

There is some kind of reactivity bug which can cause mutations to be called for the wrong workflow.

<img width="913" alt="Screenshot 2021-06-21 at 11 54 34" src="https://user-images.githubusercontent.com/16705946/122751570-db80c780-d287-11eb-9ca3-cf62a3b931fe.png">

**Steps to reproduce the bug**

1. Open the tree view to one workflow.
2. Open the mutation editor for a the workflow via the workflow toolbar.
3. The workflow ID should match.
4. Switch to another workflow.
5. Open the mutation editor again, the workflow ID does not match.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
This bug is on master, I had hoped #543 would fix this inadvertently, however, the above screenshot was taken on that branch so will have to hunt this one down.

**Comment by oliver-sanders** [comment]
Got it, the directive needs to be responsive, SO post with responsive example - https://stackoverflow.com/questions/47200760/vuejs-directive-two-way-binding

**Comment by kinow** [comment]
> Got it, the directive needs to be responsive, SO post with responsive example - https://stackoverflow.com/questions/47200760/vuejs-directive-two-way-binding

Ah, good catch! Thanks for the PR!
