### ISSUE TITLE
task: differentate running and submitted icons

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#701]
The submitted task icon is the same as the running task icon (just with no progress).

This is by design, however, it would help to differentiate them a little.

* [x] When a task has started running we should advance the "progress" animation forward a tick or two so that the clock face is visible.
* [ ] https://github.com/cylc/cylc-ui/issues/608
* [ ] #922

![Screenshot from 2021-07-06 10-03-46](https://user-images.githubusercontent.com/16705946/124573473-7ad5bb00-de41-11eb-9acd-698c04aee3b5.png)

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
@wxtim why does this have the blocked label?

**Comment by MetRonnie** [comment]
Removing the blocked label as there doesn't seem to be a reason for it

**Comment by wxtim** [comment]
I have no idea - September was 5 months ago!

**Comment by oliver-sanders** [comment]
Converted the last point into an issue.

Closing this as superseeded by the issues that replace it, #608, #922
