### ISSUE TITLE
gscan: workflow state sorting bug

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#702]
GScan can get confused when workflows change state.

Here's a screenshot showing a running workflow shown at the bottom of the GScan list (should be at the top):

![Screenshot from 2021-07-06 12-34-39](https://user-images.githubusercontent.com/16705946/124593762-f1c97e80-de56-11eb-8213-2211c1091198.png)

When the page is refreshed it appears at the top:

![Screenshot from 2021-07-06 12-34-59](https://user-images.githubusercontent.com/16705946/124593779-f5f59c00-de56-11eb-9a5e-d4693992a76b.png)

Steps to reproduce:

* Install two workflows.
* Navigate to the second workflow (in the sort order) in GScan.
* Start it.

**Pull requests welcome!**

**Comment by kinow** [comment]
Reproduced the bug. Really strange, but hopefully easy to fix. :neckbeard:
