### ISSUE TITLE
toolbar: buttons not active when they should be

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#753]
The play/pause/stop button toggling seems to have got out of sync with cylc-flow.

Perhaps the enums have changed format or the installed state isn't handled properly or something like that.

* When I install a workflow the pause button appears rather than the play button.
* When I stop a workflow the pause button appears rather than the play button and is not active.

**Comment by kinow** [comment]
Maybe related/duplicated of #748

**Comment by oliver-sanders** [comment]
Yep, thanks.
