### ISSUE TITLE
Ideas for improving the tree view

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#769]
**Describe exactly what you would like to see in an upcoming release**
- [ ] A tooltip that appears when you hover over a task's state icon, telling you what the state is in case you don't know what the icon means
  - E.g. I wasn't sure what the icon meant here with the dot outside the circle (it means runahead)
  
    ![image](https://user-images.githubusercontent.com/61982285/133269546-9afcbdee-17a5-4630-8f4d-2ef9a990f8e2.png)

- [x] (#805) A "pill" type annotation next to the workflow run name, showing the state of the workflow, whether it's "running", "paused", "finished", "stopped - REQUEST(CLEAN)" etc. I know this is already in the Gscan, but it might be useful to have on the tree view page too.
  - Quick mockup (modified GitHub UI in devtools):
  
    ![image](https://user-images.githubusercontent.com/61982285/133270335-391dda66-da45-45a9-92db-93618848fac5.png)

**Pull requests welcome!**

**Comment by hjoliver** [comment]
:+1:

**Comment by oliver-sanders** [comment]
> A tooltip that appears when you hover over a task's state icon

Tooltips have some drawbacks (especially as users interact with tasks by clicking on them), perhaps we could incorporate a status message into the context menu. Here's an example derived from the design document (a little out of date in some ways now) where I've added the graph node representation and a status line above the divider:

![task-menu-info](https://user-images.githubusercontent.com/16705946/134508330-738235c5-1993-46bb-b174-d713ac6d1849.png)

So for a runahead task the status line could be "Task help back by runahead limit".

(Note this information should be available for all views)

> A "pill" type annotation next to the workflow run name

I think this information should be present in the workflow status string, here's a snippet from the design document:

![toolbar-snip](https://user-images.githubusercontent.com/16705946/134509700-b74f5587-6f26-410d-b0a7-0bdb7bc20702.png)

So for a paused workflow the status string could be "Paused".

**Comment by hjoliver** [comment]
> Tooltips have some drawbacks ...

(And for mobile devices)

**Comment by oliver-sanders** [comment]
See also the proposed "task status message" which is used in the above mock-up.

https://github.com/cylc/cylc-flow/issues/4486

**Comment by MetRonnie** [comment]
Bumping to 1.x because I think it will take some time to figure out achieving this in the context menu. Need to focus on cylc 8.0rc1 for now
