### ISSUE TITLE
Create views off the data store (instead of only using initial-data-burst)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#803]
**Describe exactly what you would like to see in an upcoming release**

At the moment the views like Tree and Table view are created using Vuex store properties. These properties are only ever initialized from GraphQL initial-data-burst messages.

Note that the data in the Vuex store that we use is derived from GraphQL data. e.g. the Tree View doesn't use GraphQL data directly. The GraphQL endpoint doesn't provide hierarchical data. Instead, there is some code that creates a hierarchical data structure with pointers to the GraphQL original data.

**Additional context**

The challenge here, then, is to think in a way to create the derived data structure in an intelligent manner. 

We could identify we already have a compatible subscription (i.e. same query used in 2 views), and then just call the code that creates the derived data structure.

Or we could find a way to tie-together the original GraphQL data & the derived data, so that components/views only use the derived data directly (as they are doing now).

The last option is to always refresh a subscription.

>NOTE: we identified this issue in #631 where we added a Table View, but already had a Tree View; the two queries are pretty much the same, so merging them results in the same query. See the Table View PR's & issue for more.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Here's a slightly clearer explanation of what I'm describing:

<img src="https://user-images.githubusercontent.com/16705946/137319488-e9f9b567-7b5b-41ce-b5bf-e9c545757f11.png" width="50%"/>

* The views register their subscriptions with the data backend.
* The data backend merges these subscriptions and subscribes to the result.
* The backend updates the flat and tree stores for every delta that comes in.
* The views use one of these stores and rely on Vue reactivity for their updates.
* The views never see the deltas, the initial data burst or anything GraphQL, they only see the store.

We would need some extra housekeeping logic to remove data from the store when we are no longer looking at it. We could do this crudely by removing `tasks`, `taskProxies`, etc when there are no longer any active subscriptions to them (i.e. when the user navigates away).

> One issue is that we don't always have the reactivity

Ooh, where do we not have reactivity?

> and also create reactively the data structure for the tree.
> we know now that we want to update the raw data, and both tree and table data structures.
> So we have an occasionally reactive dependency between the raw data, and the table and tree data structure

I think the easy solution is to maintain the flat and tree structures in the store all the time. We can always optimise this later.

(with the current structure I think we will need a graph structure in the store to hold the edge relationships, although we could move that into the task/family proxy sections of the schema to avoid this?)

> One possible simple fix could be to keep things as they are, do not merge the query, but add the callbacks for the new widget

I don't think we need to separate the subscriptions, we can blindly update the flat and tree stores with whatever data comes in. The views may have to filter the store data to account for this.

We can always optimise this later to avoid updating things we don't need to.

**Comment by hjoliver** [comment]
Closed by #672 ??
