### ISSUE TITLE
Change route for Suite view to use suite/workflow ID

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#83]
Still calling it Suite until #73 is done.

_Note about routes: We use [Vue Router](https://router.vuejs.org/) for [routing in Vue.js](https://vuejs.org/v2/guide/routing.html) (which can actually be done with other libraries. The `/user/$username/` part of the URL is handled by Tornado. And we use the mode "hash" mode, hence the `/#/` in the URLs... after this part, that's Vue.js routing. The other mode "history" needs a web server for URL rewriting IIRC._

At the moment from the Dashboard view `/user/$username/#/?` the user goes to the Suites view `/user/$username/#/suites`, then chooses a suite and finally reaches the Suite view. This is literally the name of the view in Vue that [we have](https://github.com/cylc/cylc-ui/blob/cb9538c9d25bf07185d59226643eaceb241e2748/src/views/Suite.vue).

The URL for the Suite view is `/user/$username/#/suites/$suitename`. In the GraphQL model, in the response, the suites (workflow there) have an ID comprised of `owner/workflowname`. This information is necessary to identify suites that could have the same name, but started by different users.

__The task here is to change the route and the links in the Suites view to point to `/user/$username/#/suites/$suiteid`__.

Here's an example of what we have now:

- `http://localhost:8000/user/kinow/#/suites/five`

But we need to have:

- `http://localhost:8000/user/kinow/#/suites/kinow/five`

The user name will appear twice in the URL, and while it looks redundant, that's correct, as the `kinow/five` is the suite/workflow ID, and later it could change to something like `kinow.five`, `kinow-five`, `1224324hjkhk42`, etc (though unlikely).

The routes of our Vue.js are defined [in this file](https://github.com/cylc/cylc-ui/blob/cb9538c9d25bf07185d59226643eaceb241e2748/src/router/paths.js). The link from the Suites view is [defined here](https://github.com/cylc/cylc-ui/blob/cb9538c9d25bf07185d59226643eaceb241e2748/src/views/Suites.vue#L121) and will need to match whatever is set as new value.

Cheers
Bruno

**Comment by hjoliver** [comment]
Note also the user name is not redundant because the first name is the authenticated user, the second is the suite owner.  They are usually the same person, but not necessarily.

**Comment by kinow** [comment]
Oh yeah, forgot to mention it. We could have a URL like `/user/kinow/#/suites/hjoliver/five`, where it is clear why we need the owner/suitename pattern in the URL.

**Comment by kinow** [comment]
Superseded by #73

**Comment by kinow** [comment]
And there is a URL `/#/workflows`, as well as a `/#/workflows/$ID`... though being routed through other components/services, but these are the replacements for the previous Suite equivalents.
