### ISSUE TITLE
UI response to a fire-hose of deltas?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#834]
My test workflow:
```ini
[task parameters]
  m = 0..10
[scheduling]
  cycling mode = integer
  initial cycle point = 1
  runahead limit = P5
  [[graph]]
     P1 = foo => FAM:succeed-all => bar
[runtime]
   [[root]]
      script = "sleep $((RANDOM % 10))"
   [[foo, bar]]
   [[FAM]]
   [[f<m>]]
      inherit = FAM
```

This is small-ish but busy. With local jobs on a multi-core HPC node (to avoid overloading the scheduler host) it submitted ~600 jobs in ~7 mins, out to cycle point 46. Browser running on my desktop box.

Running with `cylc play --no-detach` you can easily compare the GUI with terminal output to see if the GUI is keeping up.

At first (for 20-ish cycles) the UI keeps up with the scheduler.  But gradually it starts getting behind, and showing an increasing number of seemingly spurious succeeded tasks (with no jobs) way behind the scheduler, plus empty cycle points with a `?` icon, like this:
![shot](https://user-images.githubusercontent.com/2362137/139961008-0f49e2f3-2492-40f4-a9b0-337ce3a5ec16.png)

A short while later, all that's left is the `?` cycle points:
![shot](https://user-images.githubusercontent.com/2362137/139961119-c334730e-a2ec-4afb-b3ea-6c86880f8f20.png)

Finally, after pausing (or in fact stopping) the workflow, the UI slowly catches up, looking increasingly normal until the final state appears to be correct:
![shot](https://user-images.githubusercontent.com/2362137/139961631-caf238b5-ae17-4956-b02f-1f085ff01337.png)

**Comment by hjoliver** [comment]
(This is current UI master branch, with @dwsutherland's current delta fix PRs on the back end).

## tentative conclusions

The UI:
- initially looks normal
- then gets behind and increasingly weird
- but finally catches up to the correct state if the delta stream is stopped

This suggests(?):
- The deltas are now correct (right order, no duplicates etc.), and are being processed in the right order (and with no gaps) in the UI, resulting in a correct UI data store - otherwise we should not expect the final state of the UI to be correct once the delta stream slows off, BUT
-  *The UI (or the UIS?) can't process the deltas fast enough* (hence getting left behind by the scheduler)
-  and *the browser can't render the display fast enough for the rate of changes coming to it?*

**Comment by hjoliver** [comment]
We need to understand exactly what's happening here.

Suggestion from @oliver-sanders (in meeting) the UI should monitor rate of delta processing (gaps between deltas indicate everything is OK) and/or size of the delta queue, and warn the user if it can't keep up with the scheduler.

**Comment by kinow** [comment]
>The UI (probably not the UIS?) can't process the deltas fast enough (hence getting left behind by the scheduler)
>and the browser can't render the display fast enough for the rate of changes coming to it?

Both possible I guess. If we cannot batch deltas in the UIS, here's a few ideas:

1. Check the time spent in "Scripting" in the browser performance tools (if you use dev mode, with a sourcemap, you can even try to look at the functions that are taking long to complete) - this could show if the UI is slow because of the time to process deltas
2. Check the frame rate in the performance tool. Normally 60fps is what most apps try to achieve. I think that means < 16 milliseconds per render. So use the performance tool to trace a delta being applied (you can use offline mode) and confirm the render operation in the browser is below that threshold (if not, the UI could be lagging to render elements affected by the deltas)
3. Maybe just `debounce` the Vue app, so that it only modifies the VDOM in certain intervals; Martin had done that in the graph intuitively, as it's quite normal to debounce operations like updating a tree/canvas/table/etc. This could improve the performance, even if the user is not able to see all the deltas happening (i.e. maybe it won't show preparing or submitted, and will go straight to succeeded or failed etc)
4. Create a live expression in the browser to monitor the number of deltas. Live expressions are created with the "eye" in the development tools of Chrome/Ffox. Just hack the `WorkflowService` and expose the number of deltas or something that can be used as an indicator to when the UI starts to lag.

If you suspect of something in the UI, a good way to confirm the hypothesis is:

1. `yarn run serve` (to have offline mode)
2. craft one or more deltas to be submitted
3. start the browser performance tools
3. paste the code in the browser console, and see if the browser performance tools agrees with the hypothesis (you should be able to confirm that by looking at memory heap, time to render, number of times the UI was repainted, scripting time, etc...)

p.s. I think the simplest might be to keep applying the deltas, but control when Vue updates the VDOM & DOM, with a debounce or a similar mechanism :+1:

**Comment by hjoliver** [comment]
Thanks @kinow excellent suggestions!

**Comment by hjoliver** [comment]
(I may even attempt a few of them myself :grin: )

**Comment by dwsutherland** [comment]
Found the issue:
https://github.com/cylc/cylc-flow/blob/d01ae7d60ae56f94b8d75d7318f810bfcf1fcb8c/cylc/flow/network/resolvers.py#L456
The UIS sleeps for too long, you can see it with this print:
```
                    for flow_id, flow_queue in flow_delta_queues.items():
                        if flow_queue.empty():
                            continue
                        elif flow_id in delta_processing_flows:
                            if counters[flow_id] < DELTA_PROC_WAIT:
                                if delta_yield_queue.empty():
                                    counters[flow_id] += 1
                                    print(f'delta still proccessing {time()}')
                                    await asyncio.sleep(DELTA_SLEEP_INTERVAL)
                                continue
                            delta_processing_flows.remove(flow_id)
                        counters[flow_id] = 0
                        topic, delta_store = flow_queue.get()
                        delta_yield_queue.put((flow_id, topic, delta_store))
```
stopping it, it takes 20sec to get through the deltas (after a few min of running):
```
[I 2021-11-03 16:53:06.431 CylcHubApp log:189] 200 POST /user/sutherlander/cylc/graphql (sutherlander@::ffff:127.0.0.1) 10.58ms
1635911586.6636074 - graphql still processing delta
1635911586.6658988 - graphql still processing delta
1635911587.6739895 - graphql still processing delta
1635911587.6740754 - graphql still processing delta
1635911588.6793842 - graphql still processing delta
1635911588.6823034 - graphql still processing delta
1635911589.701124 - graphql still processing delta
1635911589.7011757 - graphql still processing delta
1635911590.7068245 - graphql still processing delta
1635911590.7068894 - graphql still processing delta
1635911591.7090294 - graphql still processing delta
1635911591.7091057 - graphql still processing delta
1635911592.7169018 - graphql still processing delta
1635911592.7170086 - graphql still processing delta
1635911593.7530007 - graphql still processing delta
1635911593.7530594 - graphql still processing delta
1635911594.7677276 - graphql still processing delta
1635911594.7696364 - graphql still processing delta
1635911595.771665 - graphql still processing delta
1635911595.7717202 - graphql still processing delta
1635911596.7740169 - graphql still processing delta
1635911596.7740667 - graphql still processing delta
1635911597.7869205 - graphql still processing delta
1635911597.7869873 - graphql still processing delta
1635911598.7955997 - graphql still processing delta
1635911598.7956743 - graphql still processing delta
1635911599.828826 - graphql still processing delta
1635911599.8289022 - graphql still processing delta
1635911600.831748 - graphql still processing delta
1635911600.8318102 - graphql still processing delta
1635911601.8346593 - graphql still processing delta
1635911601.8347533 - graphql still processing delta
1635911602.8504155 - graphql still processing delta
1635911602.8505185 - graphql still processing delta
1635911603.8621857 - graphql still processing delta
1635911603.8622513 - graphql still processing delta
1635911604.865148 - graphql still processing delta
1635911604.8652153 - graphql still processing delta
1635911605.8741736 - graphql still processing delta
1635911605.87424 - graphql still processing delta
1635911606.878853 - graphql still processing delta
1635911606.878909 - graphql still processing delta
1635911607.8896484 - graphql still processing delta
1635911607.8897295 - graphql still processing delta
1635911608.901752 - graphql still processing delta
1635911608.9018135 - graphql still processing delta
1635911609.90526 - graphql still processing delta
1635911609.905324 - graphql still processing delta
```
Reducing this sleep from 0.5 to 0.1 shortens this time:
```
[I 2021-11-03 17:04:01.690 CylcHubApp log:189] 200 POST /user/sutherlander/cylc/graphql (sutherlander@::ffff:127.0.0.1) 17.45ms
1635912241.8879893 - graphql still processing delta
1635912242.2932487 - graphql still processing delta
1635912242.4930043 - graphql still processing delta
1635912242.897799 - graphql still processing delta
1635912243.0972733 - graphql still processing delta
1635912243.7068768 - graphql still processing delta
1635912251.86888 - graphql still processing delta
1635912252.0610445 - graphql still processing delta
1635912252.654349 - graphql still processing delta
1635912252.6672826 - graphql still processing delta
```
The sleep was there to make sure a delta doesn't get stuck processing, so to carry on after some time.. (not sure this could happen, but just in case).

Will think of a different solution, and create a PR.

**Comment by hjoliver** [comment]
Good news @kinow, with @dwsutherland 's cylc-flow tweak, the UI is now performing **perfectly** on this extremely busy example :tada: :relieved: 

(I must say I don't understand how the yied delay caused the above symptoms in the UI, but will worry about that later!)

**Comment by hjoliver** [comment]
(I'm going to record your debugging advice for later though, or compare with existing notes at least :+1: )

**Comment by hjoliver** [comment]
Even better, I just ran the gnarly "complex" worklfow (in Cylc 7 back compat mode too, which pre-spawns a bunch of waiting tasks into the active scheduler pool) - albeit with a queue limit of 6 as running local jobs on my laptop VM, and the UI looked to perform perfectly on that too (hard to be sure with so many tasks in play, but I didn't notice any problem, and the UI definitely kept up with the scheduler. :tada:

**Comment by dwsutherland** [comment]
> (I must say I don't understand how the yield delay caused the above symptoms in the UI, but will worry about that later!)

The delay was artificially imposed by me, because I wanted to give it time to process before checking again.. But I removed it completely (as it was a silly place to put it), and just hooked into the main `queue.Empty` section to track/limit delta processing time... So now it should run at full speed.

**Comment by hjoliver** [comment]
Yeah, but would that have just delayed the deltas getting to the UI?  If so, I'd expect the UI to get behind, but not get into a weird state like that shown above in the screenshots.

**Comment by dwsutherland** [comment]
> Yeah, but would that have just delayed the deltas getting to the UI? If so, I'd expect the UI to get behind, but not get into a weird state like that shown above in the screenshots.

If it's not doing it anymore, then I think it may have been yielding the next delta too early (?) (if the count got too high).. I did notice a similar thing before this fix.. If we notice anymore we'll need to look at the deltas to see why.

**Comment by dwsutherland** [comment]
It also could be reaching a queue limit and dropping some? .. not sure
