### ISSUE TITLE
disable unauthorized buttons: follow up

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#840]
(hopefully small) Follow on work from https://github.com/cylc/cylc-ui/pull/728 (cut off by release).

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Authorized actions should probably rise to the top of the list (I think I saw, during testing, it was possible for all of the "see less" items to be greyed out, and I had to click on "see more" to see authorized ones).

**Comment by oliver-sanders** [comment]
We talked about this at our end, there is a good argument for keeping things in the place where people expect to find them to avoid confusion.

**Comment by oliver-sanders** [comment]
Swallowed by other work...
