### ISSUE TITLE
Instant filtering (by task name/state)

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#853]
**Describe exactly what you would like to see in an upcoming release**

Instead of having to click a button to implement the filter, why not instantly filter? (For the task name, which is typed out, this would have to be debounced)

Marked as question in case there is a reason not to do this.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
No reason, just a usability feature yet to be implemented.

**Comment by hjoliver** [comment]
Implemented in #861
