### ISSUE TITLE
make mutations available in all places

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#867]
"Cylc Objects" are things that have Cylc ID's such as workflows, cycles, tasks & jobs.

All Cylc objects can be made "mutable" by adding the `cylc-object` directive to the relevant component.

This adds the on-click menu which is automatically propagated with the appropriate mutations.

The tree view currently implements mutations for all "Cylc Objects", however, I don't think other views do.

We need to go through and add the directive where appropriate, taking care to avoid any conflict with other on-click interactivity & tooltips.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
> The tree view currently implements mutations for all "Cylc Objects", however, I don't think other views do.
 
table view (is this all you meant?):

![shot](https://user-images.githubusercontent.com/2362137/145471098-676a964d-584b-401f-942f-bd93ea82d821.png)

**Comment by oliver-sanders** [comment]
> table view (is this all you meant?):

Great, just GScan left then.
