### ISSUE TITLE
Mutations form "add item" button should give focus to added input

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#890]
Pressing the "add item" button should give focus to the newly added input field.

<img src="https://user-images.githubusercontent.com/61982285/150573368-70283e91-c40c-4556-8cde-8d1eb5c161f1.png" width="400">

**Pull requests welcome!**

**Comment by AaronDCole** [comment]
https://github.com/cylc/cylc-ui/pull/919
