### ISSUE TITLE
Received a Table delta before the workflow initial data burst

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#903]
When you have the Table View open and a workflow shuts down automatically due to finishing, an error appears:
> Received a Table delta before the workflow initial data burst

<img src="https://user-images.githubusercontent.com/61982285/151360516-0d43589d-ee78-499e-8e2d-96426118c533.png">

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
Will probably get fixed by the move to centralised data tree for all views

**Comment by dwsutherland** [comment]
> The problem seems to be there are 4 empty deltas that come through after the workflow shuts down, when in the Table view. This doesn't happen for the Tree view. By empty I mean
> 
> ```
> deltas = {
>   added: {},
>   updated: {},
>   pruned: {}
> }
> ```
> 
> I don't know why this is happening

So the process coming from the UIS is:
- delta arrives that contains something
- this is packaged and yielded to the graphql machinery.
- graphql machinery reduces this to only the fields you've selected.
- if the fields you've selected are empty it will strip them (if `stripNull` is used)
- the result is pushed through to the UI/client.

So not sure what to do about it really.. possibly add more bespoke `stripNull` filters before the websocket push.. 

Without testing (and off the top of my head), I'd say if other fields where in the graphql doc it would return something  (probably some sort of shutdown messages)

Other option is to deal with it at the UI, the fact they are empty is probably caught by the current UI logic as not a initial dump so assumed to be an update (to a non-existent workflow), and hence the error message.
