### ISSUE TITLE
Mutations menu (`CylcObjectMenu`) duplicated

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#904]
The mutations menu is rendered twice, one on top of the other. I don't know why.

In the normal devtools:

<img src="https://user-images.githubusercontent.com/61982285/151406811-baab3de1-0e84-4453-9b6c-e113a4385aa5.png" width="600">

In the Vue devtools:

<img src="https://user-images.githubusercontent.com/61982285/151406924-068573d4-7252-4bc6-b849-7ede651df7de.png" width="550">

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by AaronDCole** [comment]
https://github.com/cylc/cylc-ui/pull/912

Hopefully this fixes the issue, I think we only need 'one' instance of the CylcObjectMenu as the 'popup' is triggered on every instance regardless of where it is in the application.
