### ISSUE TITLE
Better error notification

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#91]
If polling is enabled (or if we have websockets and an error happens multiple times) we need to be smart on how to display errors... with polling, but with the UI Server down, my UI displayed way too many errors at once.

![Screenshot_2019-06-22_16-57-43](https://user-images.githubusercontent.com/304786/59966633-34230a00-9573-11e9-9551-59f0fa1d70ed.png)

**Comment by matthewrmshin** [comment]
Need some stars on one side...

**Comment by sadielbartholomew** [comment]
I've just ran into that to :laughing:!
![spawning_errors](https://user-images.githubusercontent.com/30274190/60756768-92330100-9ff9-11e9-932a-c68811cf74cf.png)

**Comment by kinow** [comment]
This should not happen any longer, so closing it :+1:

**Comment by kinow** [comment]
Fixed in #108
