### ISSUE TITLE
gscan: only one level of the hierarchy is displayed

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#930]
The workflow `a/b/c/d` displays differently at 0.6.0 to 1.0.0:

**0.6.0**

![0 6 0](https://user-images.githubusercontent.com/16705946/154292588-1bcc876f-2c76-49d8-b3d5-322cab523372.png)

**1.0.0**

![1 0 0](https://user-images.githubusercontent.com/16705946/154292611-f74fde4b-1c13-4ecd-b9a7-da62d8d366da.png)

The 0.6.0 UI is correctly displaying all levels of the hierarchy whereas the 1.0.0 UI is only displaying one level.

This suggests we have a gap in testing which should be filled by the fix.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Not release blocking as all workflows are still displayed, just flat after the first level, e.g:

```console
$ tree a
a
`-- b
    |-- c
    |   `-- d
    |       `-- suite.rc
    `-- e
        `-- suite.rc

```

![end](https://user-images.githubusercontent.com/16705946/154293800-93ad3000-5119-45f3-8308-c8532db3059c.png)

**Comment by wxtim** [comment]
I have duplicated this bug.

**Comment by hjoliver** [comment]
Presumably this goes to show we aren't using hierarchical paths in our personal test workflows (and auto testing).

**Comment by MetRonnie** [comment]
> Presumably this goes to show we aren't using hierarchical paths in our personal test workflows (and auto testing).

It might be a good idea to make the demo mode (`yarn run serve`) have such a workflow

**Comment by oliver-sanders** [comment]
> Presumably this goes to show we aren't using hierarchical paths in our personal test workflows (and auto testing).

The functional and integration tests are both registered hierarchically so we should have spotted this earlier.
