### ISSUE TITLE
replace changelog with link to milestone

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#937]
I'm not sure it's useful to have a changelog for a web app. Unless it's visible from within the app itself it won't be looked at.

All changes are documented in the milestones anyway.

Don't see the point of maintaining a changelog no one will look at.

**Comment by hjoliver** [comment]
Fair point. Do other web projects do this?

**Comment by hjoliver** [comment]
However, change logs are written specifically as a concise user-readable summary, with links to the details.

If we ditch that, we'd better put more effort into making issue titles and descriptions more user friendly.

**Comment by hjoliver** [comment]
Another option? Keep the change log but incorporate it into the UI.

**Comment by oliver-sanders** [comment]
> Another option? Keep the change log but incorporate it into the UI.

When did you last read a changelog for a web app?

Can do, however, should make it much less verbose to be useful.

**Comment by oliver-sanders** [comment]
Superseded by https://github.com/cylc/cylc-doc/issues/314
