### ISSUE TITLE
dependabot: replace with renovate

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#944]
Yarn berry support for Dependabot doesn't seem to be happening.

Switch over to [Renovate](https://github.com/renovatebot/renovate).

https://github.com/apps/renovate

**Comment by oliver-sanders** [comment]
We have one decision to make, we current use semantic version ranges to define our package.json. To continue with this approach use the following `renovate.json`:

```json
{
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "matchPackagePatterns": [
        "*"
      ],
      "rangeStrategy": "replace"
    }
  ]
}
```

Otherwise Renovate will hard-pin every dependency. Semver is probably better when managing dependencies by hand, hard-pinning better when managing dependencies by bot. Happy to go either way.

**Comment by MetRonnie** [comment]
I had actually forgotten that the caret (`^`) worked this way: https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by MetRonnie** [comment]
How does Renovate know when to/not to upgrade a package if we use a hard-pin version?

**Comment by oliver-sanders** [comment]
Same way as if we loosely pin it, like dependabot it's a simple system for detecting when things are out of date and bumping them accordingly.

**Comment by MetRonnie** [comment]
Ah, I see dependabot didn't adhere to the `^`s and `~`s anyway

**Comment by oliver-sanders** [comment]
This [diff](https://github.com/cylc/cylc-ui/pull/1000/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R28-R36) and these [PRs](https://github.com/oliver-sanders/cylc-ui/pulls) (ignore the Dependabot ones) show the kind of changes Renovate makes when adhering to semantic version rules, basically just bumps minor versions and presumably maintenance versions when CVEs are issued?

If we swap it over to hard-pinning we'll get a PR like [this one](https://github.com/oliver-sanders/cylc-ui/pull/23) and, presumably subsequent PRs for every maintenance release. Because the version ranges are tighter vulnerability scanning is presumably easier?

**Comment by oliver-sanders** [comment]
We could always get started with semantic versioning turned on (requires no changes) and reconsider later but if there's an obvious preference we might as well do it now.

**Comment by MetRonnie** [comment]
I would say stick with semver for now, no-one is screaming either way. Are you going to push the required config to #1007?

**Comment by oliver-sanders** [comment]
Done.
